%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.13.0

-ifndef(client_log).
-define(client_log, true).

-define(client_log_gpb_version, "4.13.0").

-ifndef('PB_CLIENT_LOG_PB_H').
-define('PB_CLIENT_LOG_PB_H', true).
-record(pb_client_log,
        {counts = []            :: [client_log:pb_count()] | undefined, % = 1
         events = []            :: [client_log:pb_event()] | undefined % = 2
        }).
-endif.

-ifndef('PB_COUNT_PB_H').
-define('PB_COUNT_PB_H', true).
-record(pb_count,
        {namespace = <<>>       :: iodata() | undefined, % = 1
         metric = <<>>          :: iodata() | undefined, % = 2
         count = 0              :: integer() | undefined, % = 3, 64 bits
         dims = []              :: [client_log:pb_dim()] | undefined % = 4
        }).
-endif.

-ifndef('PB_EVENT_PB_H').
-define('PB_EVENT_PB_H', true).
-record(pb_event,
        {namespace = <<>>       :: iodata() | undefined, % = 1
         event = <<>>           :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('PB_DIM_PB_H').
-define('PB_DIM_PB_H', true).
-record(pb_dim,
        {name = <<>>            :: iodata() | undefined, % = 1
         value = <<>>           :: iodata() | undefined % = 2
        }).
-endif.

-endif.
