%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.13.0

-ifndef(privacy_list).
-define(privacy_list, true).

-define(privacy_list_gpb_version, "4.13.0").

-ifndef('PB_UID_ELEMENT_PB_H').
-define('PB_UID_ELEMENT_PB_H', true).
-record(pb_uid_element,
        {action = add           :: add | delete | integer() | undefined, % = 1, enum pb_uid_element.Action
         uid = 0                :: integer() | undefined % = 2, 64 bits
        }).
-endif.

-ifndef('PB_PRIVACY_LIST_PB_H').
-define('PB_PRIVACY_LIST_PB_H', true).
-record(pb_privacy_list,
        {type = all             :: all | block | except | mute | only | integer() | undefined, % = 1, enum pb_privacy_list.Type
         uid_elements = []      :: [privacy_list:pb_uid_element()] | undefined, % = 2
         hash = <<>>            :: iodata() | undefined % = 3
        }).
-endif.

-ifndef('PB_PRIVACY_LIST_RESULT_PB_H').
-define('PB_PRIVACY_LIST_RESULT_PB_H', true).
-record(pb_privacy_list_result,
        {result = <<>>          :: iodata() | undefined, % = 1
         reason = <<>>          :: iodata() | undefined, % = 2
         hash = <<>>            :: iodata() | undefined % = 3
        }).
-endif.

-ifndef('PB_PRIVACY_LISTS_PB_H').
-define('PB_PRIVACY_LISTS_PB_H', true).
-record(pb_privacy_lists,
        {active_type = all      :: all | block | except | integer() | undefined, % = 1, enum pb_privacy_lists.Type
         lists = []             :: [privacy_list:pb_privacy_list()] | undefined % = 2
        }).
-endif.

-endif.
