%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.13.0
-module(group_stanzas).

-export([encode_msg/1, encode_msg/2, encode_msg/3]).
-export([decode_msg/2, decode_msg/3]).
-export([merge_msgs/2, merge_msgs/3, merge_msgs/4]).
-export([verify_msg/1, verify_msg/2, verify_msg/3]).
-export([get_msg_defs/0]).
-export([get_msg_names/0]).
-export([get_group_names/0]).
-export([get_msg_or_group_names/0]).
-export([get_enum_names/0]).
-export([find_msg_def/1, fetch_msg_def/1]).
-export([find_enum_def/1, fetch_enum_def/1]).
-export([enum_symbol_by_value/2, enum_value_by_symbol/2]).
-export(['enum_symbol_by_value_pb_group_member.Action'/1, 'enum_value_by_symbol_pb_group_member.Action'/1]).
-export(['enum_symbol_by_value_pb_group_member.Type'/1, 'enum_value_by_symbol_pb_group_member.Type'/1]).
-export(['enum_symbol_by_value_pb_group_stanza.Action'/1, 'enum_value_by_symbol_pb_group_stanza.Action'/1]).
-export([get_service_names/0]).
-export([get_service_def/1]).
-export([get_rpc_names/1]).
-export([find_rpc_def/2, fetch_rpc_def/2]).
-export([fqbin_to_service_name/1]).
-export([service_name_to_fqbin/1]).
-export([fqbins_to_service_and_rpc_name/2]).
-export([service_and_rpc_name_to_fqbins/2]).
-export([fqbin_to_msg_name/1]).
-export([msg_name_to_fqbin/1]).
-export([fqbin_to_enum_name/1]).
-export([enum_name_to_fqbin/1]).
-export([get_package_name/0]).
-export([uses_packages/0]).
-export([source_basename/0]).
-export([get_all_source_basenames/0]).
-export([get_all_proto_names/0]).
-export([get_msg_containment/1]).
-export([get_pkg_containment/1]).
-export([get_service_containment/1]).
-export([get_rpc_containment/1]).
-export([get_enum_containment/1]).
-export([get_proto_by_msg_name_as_fqbin/1]).
-export([get_proto_by_service_name_as_fqbin/1]).
-export([get_proto_by_enum_name_as_fqbin/1]).
-export([get_protos_by_pkg_name_as_fqbin/1]).
-export([gpb_version_as_string/0, gpb_version_as_list/0]).

-include("group_stanzas.hrl").
-include("gpb.hrl").

%% enumerated types
-type 'pb_group_member.Action'() :: add | remove | promote | demote | leave.
-type 'pb_group_member.Type'() :: member | admin.
-type 'pb_group_stanza.Action'() :: set | get | create | delete | leave | change_avatar | change_name | modify_admins | modify_members | auto_promote_admins.
-export_type(['pb_group_member.Action'/0, 'pb_group_member.Type'/0, 'pb_group_stanza.Action'/0]).

%% message types
-type pb_group_member() :: #pb_group_member{}.

-type pb_group_stanza() :: #pb_group_stanza{}.

-type pb_group_chat() :: #pb_group_chat{}.

-export_type(['pb_group_member'/0, 'pb_group_stanza'/0, 'pb_group_chat'/0]).

-spec encode_msg(#pb_group_member{} | #pb_group_stanza{} | #pb_group_chat{}) -> binary().
encode_msg(Msg) when tuple_size(Msg) >= 1 -> encode_msg(Msg, element(1, Msg), []).

-spec encode_msg(#pb_group_member{} | #pb_group_stanza{} | #pb_group_chat{}, atom() | list()) -> binary().
encode_msg(Msg, MsgName) when is_atom(MsgName) -> encode_msg(Msg, MsgName, []);
encode_msg(Msg, Opts) when tuple_size(Msg) >= 1, is_list(Opts) -> encode_msg(Msg, element(1, Msg), Opts).

-spec encode_msg(#pb_group_member{} | #pb_group_stanza{} | #pb_group_chat{}, atom(), list()) -> binary().
encode_msg(Msg, MsgName, Opts) ->
    case proplists:get_bool(verify, Opts) of
      true -> verify_msg(Msg, MsgName, Opts);
      false -> ok
    end,
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
      pb_group_member -> encode_msg_pb_group_member(id(Msg, TrUserData), TrUserData);
      pb_group_stanza -> encode_msg_pb_group_stanza(id(Msg, TrUserData), TrUserData);
      pb_group_chat -> encode_msg_pb_group_chat(id(Msg, TrUserData), TrUserData)
    end.


encode_msg_pb_group_member(Msg, TrUserData) -> encode_msg_pb_group_member(Msg, <<>>, TrUserData).


encode_msg_pb_group_member(#pb_group_member{action = F1, uid = F2, type = F3, name = F4, avatar_id = F5, result = F6, reason = F7}, Bin, TrUserData) ->
    B1 = if F1 == undefined -> Bin;
	    true ->
		begin
		  TrF1 = id(F1, TrUserData),
		  if TrF1 =:= add; TrF1 =:= 0 -> Bin;
		     true -> 'e_enum_pb_group_member.Action'(TrF1, <<Bin/binary, 8>>, TrUserData)
		  end
		end
	 end,
    B2 = if F2 == undefined -> B1;
	    true ->
		begin
		  TrF2 = id(F2, TrUserData),
		  if TrF2 =:= 0 -> B1;
		     true -> e_type_int64(TrF2, <<B1/binary, 16>>, TrUserData)
		  end
		end
	 end,
    B3 = if F3 == undefined -> B2;
	    true ->
		begin
		  TrF3 = id(F3, TrUserData),
		  if TrF3 =:= member; TrF3 =:= 0 -> B2;
		     true -> 'e_enum_pb_group_member.Type'(TrF3, <<B2/binary, 24>>, TrUserData)
		  end
		end
	 end,
    B4 = if F4 == undefined -> B3;
	    true ->
		begin
		  TrF4 = id(F4, TrUserData),
		  case is_empty_string(TrF4) of
		    true -> B3;
		    false -> e_type_string(TrF4, <<B3/binary, 34>>, TrUserData)
		  end
		end
	 end,
    B5 = if F5 == undefined -> B4;
	    true ->
		begin
		  TrF5 = id(F5, TrUserData),
		  case is_empty_string(TrF5) of
		    true -> B4;
		    false -> e_type_string(TrF5, <<B4/binary, 42>>, TrUserData)
		  end
		end
	 end,
    B6 = if F6 == undefined -> B5;
	    true ->
		begin
		  TrF6 = id(F6, TrUserData),
		  case is_empty_string(TrF6) of
		    true -> B5;
		    false -> e_type_string(TrF6, <<B5/binary, 50>>, TrUserData)
		  end
		end
	 end,
    if F7 == undefined -> B6;
       true ->
	   begin
	     TrF7 = id(F7, TrUserData),
	     case is_empty_string(TrF7) of
	       true -> B6;
	       false -> e_type_string(TrF7, <<B6/binary, 58>>, TrUserData)
	     end
	   end
    end.

encode_msg_pb_group_stanza(Msg, TrUserData) -> encode_msg_pb_group_stanza(Msg, <<>>, TrUserData).


encode_msg_pb_group_stanza(#pb_group_stanza{action = F1, gid = F2, name = F3, avatar_id = F4, sender_uid = F5, sender_name = F6, members = F7}, Bin, TrUserData) ->
    B1 = if F1 == undefined -> Bin;
	    true ->
		begin
		  TrF1 = id(F1, TrUserData),
		  if TrF1 =:= set; TrF1 =:= 0 -> Bin;
		     true -> 'e_enum_pb_group_stanza.Action'(TrF1, <<Bin/binary, 8>>, TrUserData)
		  end
		end
	 end,
    B2 = if F2 == undefined -> B1;
	    true ->
		begin
		  TrF2 = id(F2, TrUserData),
		  case is_empty_string(TrF2) of
		    true -> B1;
		    false -> e_type_string(TrF2, <<B1/binary, 18>>, TrUserData)
		  end
		end
	 end,
    B3 = if F3 == undefined -> B2;
	    true ->
		begin
		  TrF3 = id(F3, TrUserData),
		  case is_empty_string(TrF3) of
		    true -> B2;
		    false -> e_type_string(TrF3, <<B2/binary, 26>>, TrUserData)
		  end
		end
	 end,
    B4 = if F4 == undefined -> B3;
	    true ->
		begin
		  TrF4 = id(F4, TrUserData),
		  case is_empty_string(TrF4) of
		    true -> B3;
		    false -> e_type_string(TrF4, <<B3/binary, 34>>, TrUserData)
		  end
		end
	 end,
    B5 = if F5 == undefined -> B4;
	    true ->
		begin
		  TrF5 = id(F5, TrUserData),
		  if TrF5 =:= 0 -> B4;
		     true -> e_type_int64(TrF5, <<B4/binary, 40>>, TrUserData)
		  end
		end
	 end,
    B6 = if F6 == undefined -> B5;
	    true ->
		begin
		  TrF6 = id(F6, TrUserData),
		  case is_empty_string(TrF6) of
		    true -> B5;
		    false -> e_type_string(TrF6, <<B5/binary, 50>>, TrUserData)
		  end
		end
	 end,
    begin
      TrF7 = id(F7, TrUserData),
      if TrF7 == [] -> B6;
	 true -> e_field_pb_group_stanza_members(TrF7, B6, TrUserData)
      end
    end.

encode_msg_pb_group_chat(Msg, TrUserData) -> encode_msg_pb_group_chat(Msg, <<>>, TrUserData).


encode_msg_pb_group_chat(#pb_group_chat{gid = F1, name = F2, avatar_id = F3, sender_uid = F4, sender_name = F5, timestamp = F6, payload = F7}, Bin, TrUserData) ->
    B1 = if F1 == undefined -> Bin;
	    true ->
		begin
		  TrF1 = id(F1, TrUserData),
		  case is_empty_string(TrF1) of
		    true -> Bin;
		    false -> e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData)
		  end
		end
	 end,
    B2 = if F2 == undefined -> B1;
	    true ->
		begin
		  TrF2 = id(F2, TrUserData),
		  case is_empty_string(TrF2) of
		    true -> B1;
		    false -> e_type_string(TrF2, <<B1/binary, 18>>, TrUserData)
		  end
		end
	 end,
    B3 = if F3 == undefined -> B2;
	    true ->
		begin
		  TrF3 = id(F3, TrUserData),
		  case is_empty_string(TrF3) of
		    true -> B2;
		    false -> e_type_string(TrF3, <<B2/binary, 26>>, TrUserData)
		  end
		end
	 end,
    B4 = if F4 == undefined -> B3;
	    true ->
		begin
		  TrF4 = id(F4, TrUserData),
		  if TrF4 =:= 0 -> B3;
		     true -> e_type_int64(TrF4, <<B3/binary, 32>>, TrUserData)
		  end
		end
	 end,
    B5 = if F5 == undefined -> B4;
	    true ->
		begin
		  TrF5 = id(F5, TrUserData),
		  case is_empty_string(TrF5) of
		    true -> B4;
		    false -> e_type_string(TrF5, <<B4/binary, 42>>, TrUserData)
		  end
		end
	 end,
    B6 = if F6 == undefined -> B5;
	    true ->
		begin
		  TrF6 = id(F6, TrUserData),
		  if TrF6 =:= 0 -> B5;
		     true -> e_type_int64(TrF6, <<B5/binary, 48>>, TrUserData)
		  end
		end
	 end,
    if F7 == undefined -> B6;
       true ->
	   begin
	     TrF7 = id(F7, TrUserData),
	     case iolist_size(TrF7) of
	       0 -> B6;
	       _ -> e_type_bytes(TrF7, <<B6/binary, 58>>, TrUserData)
	     end
	   end
    end.

e_mfield_pb_group_stanza_members(Msg, Bin, TrUserData) -> SubBin = encode_msg_pb_group_member(Msg, <<>>, TrUserData), Bin2 = e_varint(byte_size(SubBin), Bin), <<Bin2/binary, SubBin/binary>>.

e_field_pb_group_stanza_members([Elem | Rest], Bin, TrUserData) -> Bin2 = <<Bin/binary, 58>>, Bin3 = e_mfield_pb_group_stanza_members(id(Elem, TrUserData), Bin2, TrUserData), e_field_pb_group_stanza_members(Rest, Bin3, TrUserData);
e_field_pb_group_stanza_members([], Bin, _TrUserData) -> Bin.

'e_enum_pb_group_member.Action'(add, Bin, _TrUserData) -> <<Bin/binary, 0>>;
'e_enum_pb_group_member.Action'(remove, Bin, _TrUserData) -> <<Bin/binary, 1>>;
'e_enum_pb_group_member.Action'(promote, Bin, _TrUserData) -> <<Bin/binary, 2>>;
'e_enum_pb_group_member.Action'(demote, Bin, _TrUserData) -> <<Bin/binary, 3>>;
'e_enum_pb_group_member.Action'(leave, Bin, _TrUserData) -> <<Bin/binary, 4>>;
'e_enum_pb_group_member.Action'(V, Bin, _TrUserData) -> e_varint(V, Bin).

'e_enum_pb_group_member.Type'(member, Bin, _TrUserData) -> <<Bin/binary, 1>>;
'e_enum_pb_group_member.Type'(admin, Bin, _TrUserData) -> <<Bin/binary, 2>>;
'e_enum_pb_group_member.Type'(V, Bin, _TrUserData) -> e_varint(V, Bin).

'e_enum_pb_group_stanza.Action'(set, Bin, _TrUserData) -> <<Bin/binary, 0>>;
'e_enum_pb_group_stanza.Action'(get, Bin, _TrUserData) -> <<Bin/binary, 1>>;
'e_enum_pb_group_stanza.Action'(create, Bin, _TrUserData) -> <<Bin/binary, 2>>;
'e_enum_pb_group_stanza.Action'(delete, Bin, _TrUserData) -> <<Bin/binary, 3>>;
'e_enum_pb_group_stanza.Action'(leave, Bin, _TrUserData) -> <<Bin/binary, 4>>;
'e_enum_pb_group_stanza.Action'(change_avatar, Bin, _TrUserData) -> <<Bin/binary, 5>>;
'e_enum_pb_group_stanza.Action'(change_name, Bin, _TrUserData) -> <<Bin/binary, 6>>;
'e_enum_pb_group_stanza.Action'(modify_admins, Bin, _TrUserData) -> <<Bin/binary, 7>>;
'e_enum_pb_group_stanza.Action'(modify_members, Bin, _TrUserData) -> <<Bin/binary, 8>>;
'e_enum_pb_group_stanza.Action'(auto_promote_admins, Bin, _TrUserData) -> <<Bin/binary, 9>>;
'e_enum_pb_group_stanza.Action'(V, Bin, _TrUserData) -> e_varint(V, Bin).

-compile({nowarn_unused_function,e_type_sint/3}).
e_type_sint(Value, Bin, _TrUserData) when Value >= 0 -> e_varint(Value * 2, Bin);
e_type_sint(Value, Bin, _TrUserData) -> e_varint(Value * -2 - 1, Bin).

-compile({nowarn_unused_function,e_type_int32/3}).
e_type_int32(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int32(Value, Bin, _TrUserData) -> <<N:64/unsigned-native>> = <<Value:64/signed-native>>, e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_int64/3}).
e_type_int64(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int64(Value, Bin, _TrUserData) -> <<N:64/unsigned-native>> = <<Value:64/signed-native>>, e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_bool/3}).
e_type_bool(true, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(false, Bin, _TrUserData) -> <<Bin/binary, 0>>;
e_type_bool(1, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(0, Bin, _TrUserData) -> <<Bin/binary, 0>>.

-compile({nowarn_unused_function,e_type_string/3}).
e_type_string(S, Bin, _TrUserData) -> Utf8 = unicode:characters_to_binary(S), Bin2 = e_varint(byte_size(Utf8), Bin), <<Bin2/binary, Utf8/binary>>.

-compile({nowarn_unused_function,e_type_bytes/3}).
e_type_bytes(Bytes, Bin, _TrUserData) when is_binary(Bytes) -> Bin2 = e_varint(byte_size(Bytes), Bin), <<Bin2/binary, Bytes/binary>>;
e_type_bytes(Bytes, Bin, _TrUserData) when is_list(Bytes) -> BytesBin = iolist_to_binary(Bytes), Bin2 = e_varint(byte_size(BytesBin), Bin), <<Bin2/binary, BytesBin/binary>>.

-compile({nowarn_unused_function,e_type_fixed32/3}).
e_type_fixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little>>.

-compile({nowarn_unused_function,e_type_sfixed32/3}).
e_type_sfixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little-signed>>.

-compile({nowarn_unused_function,e_type_fixed64/3}).
e_type_fixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little>>.

-compile({nowarn_unused_function,e_type_sfixed64/3}).
e_type_sfixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little-signed>>.

-compile({nowarn_unused_function,e_type_float/3}).
e_type_float(V, Bin, _) when is_number(V) -> <<Bin/binary, V:32/little-float>>;
e_type_float(infinity, Bin, _) -> <<Bin/binary, 0:16, 128, 127>>;
e_type_float('-infinity', Bin, _) -> <<Bin/binary, 0:16, 128, 255>>;
e_type_float(nan, Bin, _) -> <<Bin/binary, 0:16, 192, 127>>.

-compile({nowarn_unused_function,e_type_double/3}).
e_type_double(V, Bin, _) when is_number(V) -> <<Bin/binary, V:64/little-float>>;
e_type_double(infinity, Bin, _) -> <<Bin/binary, 0:48, 240, 127>>;
e_type_double('-infinity', Bin, _) -> <<Bin/binary, 0:48, 240, 255>>;
e_type_double(nan, Bin, _) -> <<Bin/binary, 0:48, 248, 127>>.

-compile({nowarn_unused_function,e_varint/3}).
e_varint(N, Bin, _TrUserData) -> e_varint(N, Bin).

-compile({nowarn_unused_function,e_varint/2}).
e_varint(N, Bin) when N =< 127 -> <<Bin/binary, N>>;
e_varint(N, Bin) -> Bin2 = <<Bin/binary, (N band 127 bor 128)>>, e_varint(N bsr 7, Bin2).

is_empty_string("") -> true;
is_empty_string(<<>>) -> true;
is_empty_string(L) when is_list(L) -> not string_has_chars(L);
is_empty_string(B) when is_binary(B) -> false.

string_has_chars([C | _]) when is_integer(C) -> true;
string_has_chars([H | T]) ->
    case string_has_chars(H) of
      true -> true;
      false -> string_has_chars(T)
    end;
string_has_chars(B) when is_binary(B), byte_size(B) =/= 0 -> true;
string_has_chars(C) when is_integer(C) -> true;
string_has_chars(<<>>) -> false;
string_has_chars([]) -> false.


decode_msg(Bin, MsgName) when is_binary(Bin) -> decode_msg(Bin, MsgName, []).

decode_msg(Bin, MsgName, Opts) when is_binary(Bin) -> TrUserData = proplists:get_value(user_data, Opts), decode_msg_1_catch(Bin, MsgName, TrUserData).

-ifdef('OTP_RELEASE').
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch Class:Reason:StackTrace -> error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-else.
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch Class:Reason ->
        StackTrace = erlang:get_stacktrace(),
        error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-endif.

decode_msg_2_doit(pb_group_member, Bin, TrUserData) -> id(decode_msg_pb_group_member(Bin, TrUserData), TrUserData);
decode_msg_2_doit(pb_group_stanza, Bin, TrUserData) -> id(decode_msg_pb_group_stanza(Bin, TrUserData), TrUserData);
decode_msg_2_doit(pb_group_chat, Bin, TrUserData) -> id(decode_msg_pb_group_chat(Bin, TrUserData), TrUserData).



decode_msg_pb_group_member(Bin, TrUserData) ->
    dfp_read_field_def_pb_group_member(Bin, 0, 0, id(add, TrUserData), id(0, TrUserData), id(member, TrUserData), id(<<>>, TrUserData), id(<<>>, TrUserData), id(<<>>, TrUserData), id(<<>>, TrUserData), TrUserData).

dfp_read_field_def_pb_group_member(<<8, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_pb_group_member_action(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_pb_group_member(<<16, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_pb_group_member_uid(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_pb_group_member(<<24, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_pb_group_member_type(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_pb_group_member(<<34, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_pb_group_member_name(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_pb_group_member(<<42, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_pb_group_member_avatar_id(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_pb_group_member(<<50, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_pb_group_member_result(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_pb_group_member(<<58, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_pb_group_member_reason(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_pb_group_member(<<>>, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, _) -> #pb_group_member{action = F@_1, uid = F@_2, type = F@_3, name = F@_4, avatar_id = F@_5, result = F@_6, reason = F@_7};
dfp_read_field_def_pb_group_member(Other, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> dg_read_field_def_pb_group_member(Other, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

dg_read_field_def_pb_group_member(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 32 - 7 ->
    dg_read_field_def_pb_group_member(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dg_read_field_def_pb_group_member(<<0:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      8 -> d_field_pb_group_member_action(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      16 -> d_field_pb_group_member_uid(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      24 -> d_field_pb_group_member_type(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      34 -> d_field_pb_group_member_name(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      42 -> d_field_pb_group_member_avatar_id(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      50 -> d_field_pb_group_member_result(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      58 -> d_field_pb_group_member_reason(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      _ ->
	  case Key band 7 of
	    0 -> skip_varint_pb_group_member(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
	    1 -> skip_64_pb_group_member(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
	    2 -> skip_length_delimited_pb_group_member(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
	    3 -> skip_group_pb_group_member(Rest, Key bsr 3, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
	    5 -> skip_32_pb_group_member(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData)
	  end
    end;
dg_read_field_def_pb_group_member(<<>>, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, _) -> #pb_group_member{action = F@_1, uid = F@_2, type = F@_3, name = F@_4, avatar_id = F@_5, result = F@_6, reason = F@_7}.

d_field_pb_group_member_action(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 -> d_field_pb_group_member_action(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_pb_group_member_action(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) ->
    {NewFValue, RestF} = {id('d_enum_pb_group_member.Action'(begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end), TrUserData), Rest},
    dfp_read_field_def_pb_group_member(RestF, 0, 0, NewFValue, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

d_field_pb_group_member_uid(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 -> d_field_pb_group_member_uid(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_pb_group_member_uid(<<0:1, X:7, Rest/binary>>, N, Acc, F@_1, _, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:64/signed-native>> = <<(X bsl N + Acc):64/unsigned-native>>, id(Res, TrUserData) end, Rest}, dfp_read_field_def_pb_group_member(RestF, 0, 0, F@_1, NewFValue, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

d_field_pb_group_member_type(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 -> d_field_pb_group_member_type(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_pb_group_member_type(<<0:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, _, F@_4, F@_5, F@_6, F@_7, TrUserData) ->
    {NewFValue, RestF} = {id('d_enum_pb_group_member.Type'(begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end), TrUserData), Rest},
    dfp_read_field_def_pb_group_member(RestF, 0, 0, F@_1, F@_2, NewFValue, F@_4, F@_5, F@_6, F@_7, TrUserData).

d_field_pb_group_member_name(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 -> d_field_pb_group_member_name(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_pb_group_member_name(<<0:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, _, F@_5, F@_6, F@_7, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, {id(binary:copy(Bytes), TrUserData), Rest2} end, dfp_read_field_def_pb_group_member(RestF, 0, 0, F@_1, F@_2, F@_3, NewFValue, F@_5, F@_6, F@_7, TrUserData).

d_field_pb_group_member_avatar_id(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 ->
    d_field_pb_group_member_avatar_id(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_pb_group_member_avatar_id(<<0:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, _, F@_6, F@_7, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, {id(binary:copy(Bytes), TrUserData), Rest2} end, dfp_read_field_def_pb_group_member(RestF, 0, 0, F@_1, F@_2, F@_3, F@_4, NewFValue, F@_6, F@_7, TrUserData).

d_field_pb_group_member_result(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 -> d_field_pb_group_member_result(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_pb_group_member_result(<<0:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, _, F@_7, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, {id(binary:copy(Bytes), TrUserData), Rest2} end, dfp_read_field_def_pb_group_member(RestF, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, NewFValue, F@_7, TrUserData).

d_field_pb_group_member_reason(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 -> d_field_pb_group_member_reason(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_pb_group_member_reason(<<0:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, _, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, {id(binary:copy(Bytes), TrUserData), Rest2} end, dfp_read_field_def_pb_group_member(RestF, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, NewFValue, TrUserData).

skip_varint_pb_group_member(<<1:1, _:7, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> skip_varint_pb_group_member(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
skip_varint_pb_group_member(<<0:1, _:7, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> dfp_read_field_def_pb_group_member(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

skip_length_delimited_pb_group_member(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 ->
    skip_length_delimited_pb_group_member(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
skip_length_delimited_pb_group_member(<<0:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) ->
    Length = X bsl N + Acc, <<_:Length/binary, Rest2/binary>> = Rest, dfp_read_field_def_pb_group_member(Rest2, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

skip_group_pb_group_member(Bin, FNum, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> {_, Rest} = read_group(Bin, FNum), dfp_read_field_def_pb_group_member(Rest, 0, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

skip_32_pb_group_member(<<_:32, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> dfp_read_field_def_pb_group_member(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

skip_64_pb_group_member(<<_:64, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> dfp_read_field_def_pb_group_member(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

decode_msg_pb_group_stanza(Bin, TrUserData) ->
    dfp_read_field_def_pb_group_stanza(Bin, 0, 0, id(set, TrUserData), id(<<>>, TrUserData), id(<<>>, TrUserData), id(<<>>, TrUserData), id(0, TrUserData), id(<<>>, TrUserData), id([], TrUserData), TrUserData).

dfp_read_field_def_pb_group_stanza(<<8, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_pb_group_stanza_action(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_pb_group_stanza(<<18, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_pb_group_stanza_gid(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_pb_group_stanza(<<26, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_pb_group_stanza_name(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_pb_group_stanza(<<34, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_pb_group_stanza_avatar_id(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_pb_group_stanza(<<40, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_pb_group_stanza_sender_uid(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_pb_group_stanza(<<50, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_pb_group_stanza_sender_name(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_pb_group_stanza(<<58, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_pb_group_stanza_members(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_pb_group_stanza(<<>>, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, R1, TrUserData) ->
    #pb_group_stanza{action = F@_1, gid = F@_2, name = F@_3, avatar_id = F@_4, sender_uid = F@_5, sender_name = F@_6, members = lists_reverse(R1, TrUserData)};
dfp_read_field_def_pb_group_stanza(Other, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> dg_read_field_def_pb_group_stanza(Other, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

dg_read_field_def_pb_group_stanza(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 32 - 7 ->
    dg_read_field_def_pb_group_stanza(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dg_read_field_def_pb_group_stanza(<<0:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      8 -> d_field_pb_group_stanza_action(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      18 -> d_field_pb_group_stanza_gid(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      26 -> d_field_pb_group_stanza_name(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      34 -> d_field_pb_group_stanza_avatar_id(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      40 -> d_field_pb_group_stanza_sender_uid(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      50 -> d_field_pb_group_stanza_sender_name(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      58 -> d_field_pb_group_stanza_members(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      _ ->
	  case Key band 7 of
	    0 -> skip_varint_pb_group_stanza(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
	    1 -> skip_64_pb_group_stanza(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
	    2 -> skip_length_delimited_pb_group_stanza(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
	    3 -> skip_group_pb_group_stanza(Rest, Key bsr 3, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
	    5 -> skip_32_pb_group_stanza(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData)
	  end
    end;
dg_read_field_def_pb_group_stanza(<<>>, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, R1, TrUserData) ->
    #pb_group_stanza{action = F@_1, gid = F@_2, name = F@_3, avatar_id = F@_4, sender_uid = F@_5, sender_name = F@_6, members = lists_reverse(R1, TrUserData)}.

d_field_pb_group_stanza_action(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 -> d_field_pb_group_stanza_action(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_pb_group_stanza_action(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) ->
    {NewFValue, RestF} = {id('d_enum_pb_group_stanza.Action'(begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end), TrUserData), Rest},
    dfp_read_field_def_pb_group_stanza(RestF, 0, 0, NewFValue, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

d_field_pb_group_stanza_gid(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 -> d_field_pb_group_stanza_gid(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_pb_group_stanza_gid(<<0:1, X:7, Rest/binary>>, N, Acc, F@_1, _, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, {id(binary:copy(Bytes), TrUserData), Rest2} end, dfp_read_field_def_pb_group_stanza(RestF, 0, 0, F@_1, NewFValue, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

d_field_pb_group_stanza_name(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 -> d_field_pb_group_stanza_name(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_pb_group_stanza_name(<<0:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, _, F@_4, F@_5, F@_6, F@_7, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, {id(binary:copy(Bytes), TrUserData), Rest2} end, dfp_read_field_def_pb_group_stanza(RestF, 0, 0, F@_1, F@_2, NewFValue, F@_4, F@_5, F@_6, F@_7, TrUserData).

d_field_pb_group_stanza_avatar_id(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 ->
    d_field_pb_group_stanza_avatar_id(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_pb_group_stanza_avatar_id(<<0:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, _, F@_5, F@_6, F@_7, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, {id(binary:copy(Bytes), TrUserData), Rest2} end, dfp_read_field_def_pb_group_stanza(RestF, 0, 0, F@_1, F@_2, F@_3, NewFValue, F@_5, F@_6, F@_7, TrUserData).

d_field_pb_group_stanza_sender_uid(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 ->
    d_field_pb_group_stanza_sender_uid(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_pb_group_stanza_sender_uid(<<0:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, _, F@_6, F@_7, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:64/signed-native>> = <<(X bsl N + Acc):64/unsigned-native>>, id(Res, TrUserData) end, Rest}, dfp_read_field_def_pb_group_stanza(RestF, 0, 0, F@_1, F@_2, F@_3, F@_4, NewFValue, F@_6, F@_7, TrUserData).

d_field_pb_group_stanza_sender_name(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 ->
    d_field_pb_group_stanza_sender_name(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_pb_group_stanza_sender_name(<<0:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, _, F@_7, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, {id(binary:copy(Bytes), TrUserData), Rest2} end, dfp_read_field_def_pb_group_stanza(RestF, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, NewFValue, F@_7, TrUserData).

d_field_pb_group_stanza_members(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 -> d_field_pb_group_stanza_members(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_pb_group_stanza_members(<<0:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_pb_group_member(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_pb_group_stanza(RestF, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, cons(NewFValue, Prev, TrUserData), TrUserData).

skip_varint_pb_group_stanza(<<1:1, _:7, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> skip_varint_pb_group_stanza(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
skip_varint_pb_group_stanza(<<0:1, _:7, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> dfp_read_field_def_pb_group_stanza(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

skip_length_delimited_pb_group_stanza(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 ->
    skip_length_delimited_pb_group_stanza(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
skip_length_delimited_pb_group_stanza(<<0:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) ->
    Length = X bsl N + Acc, <<_:Length/binary, Rest2/binary>> = Rest, dfp_read_field_def_pb_group_stanza(Rest2, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

skip_group_pb_group_stanza(Bin, FNum, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> {_, Rest} = read_group(Bin, FNum), dfp_read_field_def_pb_group_stanza(Rest, 0, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

skip_32_pb_group_stanza(<<_:32, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> dfp_read_field_def_pb_group_stanza(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

skip_64_pb_group_stanza(<<_:64, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> dfp_read_field_def_pb_group_stanza(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

decode_msg_pb_group_chat(Bin, TrUserData) -> dfp_read_field_def_pb_group_chat(Bin, 0, 0, id(<<>>, TrUserData), id(<<>>, TrUserData), id(<<>>, TrUserData), id(0, TrUserData), id(<<>>, TrUserData), id(0, TrUserData), id(<<>>, TrUserData), TrUserData).

dfp_read_field_def_pb_group_chat(<<10, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_pb_group_chat_gid(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_pb_group_chat(<<18, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_pb_group_chat_name(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_pb_group_chat(<<26, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_pb_group_chat_avatar_id(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_pb_group_chat(<<32, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_pb_group_chat_sender_uid(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_pb_group_chat(<<42, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_pb_group_chat_sender_name(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_pb_group_chat(<<48, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_pb_group_chat_timestamp(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_pb_group_chat(<<58, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> d_field_pb_group_chat_payload(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dfp_read_field_def_pb_group_chat(<<>>, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, _) -> #pb_group_chat{gid = F@_1, name = F@_2, avatar_id = F@_3, sender_uid = F@_4, sender_name = F@_5, timestamp = F@_6, payload = F@_7};
dfp_read_field_def_pb_group_chat(Other, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> dg_read_field_def_pb_group_chat(Other, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

dg_read_field_def_pb_group_chat(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 32 - 7 ->
    dg_read_field_def_pb_group_chat(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
dg_read_field_def_pb_group_chat(<<0:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      10 -> d_field_pb_group_chat_gid(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      18 -> d_field_pb_group_chat_name(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      26 -> d_field_pb_group_chat_avatar_id(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      32 -> d_field_pb_group_chat_sender_uid(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      42 -> d_field_pb_group_chat_sender_name(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      48 -> d_field_pb_group_chat_timestamp(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      58 -> d_field_pb_group_chat_payload(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
      _ ->
	  case Key band 7 of
	    0 -> skip_varint_pb_group_chat(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
	    1 -> skip_64_pb_group_chat(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
	    2 -> skip_length_delimited_pb_group_chat(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
	    3 -> skip_group_pb_group_chat(Rest, Key bsr 3, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
	    5 -> skip_32_pb_group_chat(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData)
	  end
    end;
dg_read_field_def_pb_group_chat(<<>>, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, _) -> #pb_group_chat{gid = F@_1, name = F@_2, avatar_id = F@_3, sender_uid = F@_4, sender_name = F@_5, timestamp = F@_6, payload = F@_7}.

d_field_pb_group_chat_gid(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 -> d_field_pb_group_chat_gid(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_pb_group_chat_gid(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, {id(binary:copy(Bytes), TrUserData), Rest2} end, dfp_read_field_def_pb_group_chat(RestF, 0, 0, NewFValue, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

d_field_pb_group_chat_name(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 -> d_field_pb_group_chat_name(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_pb_group_chat_name(<<0:1, X:7, Rest/binary>>, N, Acc, F@_1, _, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, {id(binary:copy(Bytes), TrUserData), Rest2} end, dfp_read_field_def_pb_group_chat(RestF, 0, 0, F@_1, NewFValue, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

d_field_pb_group_chat_avatar_id(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 -> d_field_pb_group_chat_avatar_id(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_pb_group_chat_avatar_id(<<0:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, _, F@_4, F@_5, F@_6, F@_7, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, {id(binary:copy(Bytes), TrUserData), Rest2} end, dfp_read_field_def_pb_group_chat(RestF, 0, 0, F@_1, F@_2, NewFValue, F@_4, F@_5, F@_6, F@_7, TrUserData).

d_field_pb_group_chat_sender_uid(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 ->
    d_field_pb_group_chat_sender_uid(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_pb_group_chat_sender_uid(<<0:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, _, F@_5, F@_6, F@_7, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:64/signed-native>> = <<(X bsl N + Acc):64/unsigned-native>>, id(Res, TrUserData) end, Rest}, dfp_read_field_def_pb_group_chat(RestF, 0, 0, F@_1, F@_2, F@_3, NewFValue, F@_5, F@_6, F@_7, TrUserData).

d_field_pb_group_chat_sender_name(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 ->
    d_field_pb_group_chat_sender_name(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_pb_group_chat_sender_name(<<0:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, _, F@_6, F@_7, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, {id(binary:copy(Bytes), TrUserData), Rest2} end, dfp_read_field_def_pb_group_chat(RestF, 0, 0, F@_1, F@_2, F@_3, F@_4, NewFValue, F@_6, F@_7, TrUserData).

d_field_pb_group_chat_timestamp(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 -> d_field_pb_group_chat_timestamp(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_pb_group_chat_timestamp(<<0:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, _, F@_7, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:64/signed-native>> = <<(X bsl N + Acc):64/unsigned-native>>, id(Res, TrUserData) end, Rest}, dfp_read_field_def_pb_group_chat(RestF, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, NewFValue, F@_7, TrUserData).

d_field_pb_group_chat_payload(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 -> d_field_pb_group_chat_payload(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
d_field_pb_group_chat_payload(<<0:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, _, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, {id(binary:copy(Bytes), TrUserData), Rest2} end, dfp_read_field_def_pb_group_chat(RestF, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, NewFValue, TrUserData).

skip_varint_pb_group_chat(<<1:1, _:7, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> skip_varint_pb_group_chat(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
skip_varint_pb_group_chat(<<0:1, _:7, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> dfp_read_field_def_pb_group_chat(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

skip_length_delimited_pb_group_chat(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) when N < 57 ->
    skip_length_delimited_pb_group_chat(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData);
skip_length_delimited_pb_group_chat(<<0:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) ->
    Length = X bsl N + Acc, <<_:Length/binary, Rest2/binary>> = Rest, dfp_read_field_def_pb_group_chat(Rest2, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

skip_group_pb_group_chat(Bin, FNum, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> {_, Rest} = read_group(Bin, FNum), dfp_read_field_def_pb_group_chat(Rest, 0, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

skip_32_pb_group_chat(<<_:32, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> dfp_read_field_def_pb_group_chat(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

skip_64_pb_group_chat(<<_:64, Rest/binary>>, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData) -> dfp_read_field_def_pb_group_chat(Rest, Z1, Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, TrUserData).

'd_enum_pb_group_member.Action'(0) -> add;
'd_enum_pb_group_member.Action'(1) -> remove;
'd_enum_pb_group_member.Action'(2) -> promote;
'd_enum_pb_group_member.Action'(3) -> demote;
'd_enum_pb_group_member.Action'(4) -> leave;
'd_enum_pb_group_member.Action'(V) -> V.

'd_enum_pb_group_member.Type'(1) -> member;
'd_enum_pb_group_member.Type'(2) -> admin;
'd_enum_pb_group_member.Type'(V) -> V.

'd_enum_pb_group_stanza.Action'(0) -> set;
'd_enum_pb_group_stanza.Action'(1) -> get;
'd_enum_pb_group_stanza.Action'(2) -> create;
'd_enum_pb_group_stanza.Action'(3) -> delete;
'd_enum_pb_group_stanza.Action'(4) -> leave;
'd_enum_pb_group_stanza.Action'(5) -> change_avatar;
'd_enum_pb_group_stanza.Action'(6) -> change_name;
'd_enum_pb_group_stanza.Action'(7) -> modify_admins;
'd_enum_pb_group_stanza.Action'(8) -> modify_members;
'd_enum_pb_group_stanza.Action'(9) -> auto_promote_admins;
'd_enum_pb_group_stanza.Action'(V) -> V.

read_group(Bin, FieldNum) ->
    {NumBytes, EndTagLen} = read_gr_b(Bin, 0, 0, 0, 0, FieldNum),
    <<Group:NumBytes/binary, _:EndTagLen/binary, Rest/binary>> = Bin,
    {Group, Rest}.

%% Like skipping over fields, but record the total length,
%% Each field is <(FieldNum bsl 3) bor FieldType> ++ <FieldValue>
%% Record the length because varints may be non-optimally encoded.
%%
%% Groups can be nested, but assume the same FieldNum cannot be nested
%% because group field numbers are shared with the rest of the fields
%% numbers. Thus we can search just for an group-end with the same
%% field number.
%%
%% (The only time the same group field number could occur would
%% be in a nested sub message, but then it would be inside a
%% length-delimited entry, which we skip-read by length.)
read_gr_b(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen, FieldNum)
  when N < (32-7) ->
    read_gr_b(Tl, N+7, X bsl N + Acc, NumBytes, TagLen+1, FieldNum);
read_gr_b(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen,
          FieldNum) ->
    Key = X bsl N + Acc,
    TagLen1 = TagLen + 1,
    case {Key bsr 3, Key band 7} of
        {FieldNum, 4} -> % 4 = group_end
            {NumBytes, TagLen1};
        {_, 0} -> % 0 = varint
            read_gr_vi(Tl, 0, NumBytes + TagLen1, FieldNum);
        {_, 1} -> % 1 = bits64
            <<_:64, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 8, 0, FieldNum);
        {_, 2} -> % 2 = length_delimited
            read_gr_ld(Tl, 0, 0, NumBytes + TagLen1, FieldNum);
        {_, 3} -> % 3 = group_start
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 4} -> % 4 = group_end
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 5} -> % 5 = bits32
            <<_:32, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 4, 0, FieldNum)
    end.

read_gr_vi(<<1:1, _:7, Tl/binary>>, N, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_vi(Tl, N+7, NumBytes+1, FieldNum);
read_gr_vi(<<0:1, _:7, Tl/binary>>, _, NumBytes, FieldNum) ->
    read_gr_b(Tl, 0, 0, NumBytes+1, 0, FieldNum).

read_gr_ld(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_ld(Tl, N+7, X bsl N + Acc, NumBytes+1, FieldNum);
read_gr_ld(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum) ->
    Len = X bsl N + Acc,
    NumBytes1 = NumBytes + 1,
    <<_:Len/binary, Tl2/binary>> = Tl,
    read_gr_b(Tl2, 0, 0, NumBytes1 + Len, 0, FieldNum).

merge_msgs(Prev, New) when element(1, Prev) =:= element(1, New) -> merge_msgs(Prev, New, element(1, Prev), []).

merge_msgs(Prev, New, MsgName) when is_atom(MsgName) -> merge_msgs(Prev, New, MsgName, []);
merge_msgs(Prev, New, Opts) when element(1, Prev) =:= element(1, New), is_list(Opts) -> merge_msgs(Prev, New, element(1, Prev), Opts).

merge_msgs(Prev, New, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
      pb_group_member -> merge_msg_pb_group_member(Prev, New, TrUserData);
      pb_group_stanza -> merge_msg_pb_group_stanza(Prev, New, TrUserData);
      pb_group_chat -> merge_msg_pb_group_chat(Prev, New, TrUserData)
    end.

-compile({nowarn_unused_function,merge_msg_pb_group_member/3}).
merge_msg_pb_group_member(#pb_group_member{action = PFaction, uid = PFuid, type = PFtype, name = PFname, avatar_id = PFavatar_id, result = PFresult, reason = PFreason},
			  #pb_group_member{action = NFaction, uid = NFuid, type = NFtype, name = NFname, avatar_id = NFavatar_id, result = NFresult, reason = NFreason}, _) ->
    #pb_group_member{action =
			 if NFaction =:= undefined -> PFaction;
			    true -> NFaction
			 end,
		     uid =
			 if NFuid =:= undefined -> PFuid;
			    true -> NFuid
			 end,
		     type =
			 if NFtype =:= undefined -> PFtype;
			    true -> NFtype
			 end,
		     name =
			 if NFname =:= undefined -> PFname;
			    true -> NFname
			 end,
		     avatar_id =
			 if NFavatar_id =:= undefined -> PFavatar_id;
			    true -> NFavatar_id
			 end,
		     result =
			 if NFresult =:= undefined -> PFresult;
			    true -> NFresult
			 end,
		     reason =
			 if NFreason =:= undefined -> PFreason;
			    true -> NFreason
			 end}.

-compile({nowarn_unused_function,merge_msg_pb_group_stanza/3}).
merge_msg_pb_group_stanza(#pb_group_stanza{action = PFaction, gid = PFgid, name = PFname, avatar_id = PFavatar_id, sender_uid = PFsender_uid, sender_name = PFsender_name, members = PFmembers},
			  #pb_group_stanza{action = NFaction, gid = NFgid, name = NFname, avatar_id = NFavatar_id, sender_uid = NFsender_uid, sender_name = NFsender_name, members = NFmembers}, TrUserData) ->
    #pb_group_stanza{action =
			 if NFaction =:= undefined -> PFaction;
			    true -> NFaction
			 end,
		     gid =
			 if NFgid =:= undefined -> PFgid;
			    true -> NFgid
			 end,
		     name =
			 if NFname =:= undefined -> PFname;
			    true -> NFname
			 end,
		     avatar_id =
			 if NFavatar_id =:= undefined -> PFavatar_id;
			    true -> NFavatar_id
			 end,
		     sender_uid =
			 if NFsender_uid =:= undefined -> PFsender_uid;
			    true -> NFsender_uid
			 end,
		     sender_name =
			 if NFsender_name =:= undefined -> PFsender_name;
			    true -> NFsender_name
			 end,
		     members =
			 if PFmembers /= undefined, NFmembers /= undefined -> 'erlang_++'(PFmembers, NFmembers, TrUserData);
			    PFmembers == undefined -> NFmembers;
			    NFmembers == undefined -> PFmembers
			 end}.

-compile({nowarn_unused_function,merge_msg_pb_group_chat/3}).
merge_msg_pb_group_chat(#pb_group_chat{gid = PFgid, name = PFname, avatar_id = PFavatar_id, sender_uid = PFsender_uid, sender_name = PFsender_name, timestamp = PFtimestamp, payload = PFpayload},
			#pb_group_chat{gid = NFgid, name = NFname, avatar_id = NFavatar_id, sender_uid = NFsender_uid, sender_name = NFsender_name, timestamp = NFtimestamp, payload = NFpayload}, _) ->
    #pb_group_chat{gid =
		       if NFgid =:= undefined -> PFgid;
			  true -> NFgid
		       end,
		   name =
		       if NFname =:= undefined -> PFname;
			  true -> NFname
		       end,
		   avatar_id =
		       if NFavatar_id =:= undefined -> PFavatar_id;
			  true -> NFavatar_id
		       end,
		   sender_uid =
		       if NFsender_uid =:= undefined -> PFsender_uid;
			  true -> NFsender_uid
		       end,
		   sender_name =
		       if NFsender_name =:= undefined -> PFsender_name;
			  true -> NFsender_name
		       end,
		   timestamp =
		       if NFtimestamp =:= undefined -> PFtimestamp;
			  true -> NFtimestamp
		       end,
		   payload =
		       if NFpayload =:= undefined -> PFpayload;
			  true -> NFpayload
		       end}.


verify_msg(Msg) when tuple_size(Msg) >= 1 -> verify_msg(Msg, element(1, Msg), []);
verify_msg(X) -> mk_type_error(not_a_known_message, X, []).

verify_msg(Msg, MsgName) when is_atom(MsgName) -> verify_msg(Msg, MsgName, []);
verify_msg(Msg, Opts) when tuple_size(Msg) >= 1 -> verify_msg(Msg, element(1, Msg), Opts);
verify_msg(X, _Opts) -> mk_type_error(not_a_known_message, X, []).

verify_msg(Msg, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
      pb_group_member -> v_msg_pb_group_member(Msg, [MsgName], TrUserData);
      pb_group_stanza -> v_msg_pb_group_stanza(Msg, [MsgName], TrUserData);
      pb_group_chat -> v_msg_pb_group_chat(Msg, [MsgName], TrUserData);
      _ -> mk_type_error(not_a_known_message, Msg, [])
    end.


-compile({nowarn_unused_function,v_msg_pb_group_member/3}).
-dialyzer({nowarn_function,v_msg_pb_group_member/3}).
v_msg_pb_group_member(#pb_group_member{action = F1, uid = F2, type = F3, name = F4, avatar_id = F5, result = F6, reason = F7}, Path, TrUserData) ->
    if F1 == undefined -> ok;
       true -> 'v_enum_pb_group_member.Action'(F1, [action | Path], TrUserData)
    end,
    if F2 == undefined -> ok;
       true -> v_type_int64(F2, [uid | Path], TrUserData)
    end,
    if F3 == undefined -> ok;
       true -> 'v_enum_pb_group_member.Type'(F3, [type | Path], TrUserData)
    end,
    if F4 == undefined -> ok;
       true -> v_type_string(F4, [name | Path], TrUserData)
    end,
    if F5 == undefined -> ok;
       true -> v_type_string(F5, [avatar_id | Path], TrUserData)
    end,
    if F6 == undefined -> ok;
       true -> v_type_string(F6, [result | Path], TrUserData)
    end,
    if F7 == undefined -> ok;
       true -> v_type_string(F7, [reason | Path], TrUserData)
    end,
    ok;
v_msg_pb_group_member(X, Path, _TrUserData) -> mk_type_error({expected_msg, pb_group_member}, X, Path).

-compile({nowarn_unused_function,v_msg_pb_group_stanza/3}).
-dialyzer({nowarn_function,v_msg_pb_group_stanza/3}).
v_msg_pb_group_stanza(#pb_group_stanza{action = F1, gid = F2, name = F3, avatar_id = F4, sender_uid = F5, sender_name = F6, members = F7}, Path, TrUserData) ->
    if F1 == undefined -> ok;
       true -> 'v_enum_pb_group_stanza.Action'(F1, [action | Path], TrUserData)
    end,
    if F2 == undefined -> ok;
       true -> v_type_string(F2, [gid | Path], TrUserData)
    end,
    if F3 == undefined -> ok;
       true -> v_type_string(F3, [name | Path], TrUserData)
    end,
    if F4 == undefined -> ok;
       true -> v_type_string(F4, [avatar_id | Path], TrUserData)
    end,
    if F5 == undefined -> ok;
       true -> v_type_int64(F5, [sender_uid | Path], TrUserData)
    end,
    if F6 == undefined -> ok;
       true -> v_type_string(F6, [sender_name | Path], TrUserData)
    end,
    if is_list(F7) -> _ = [v_msg_pb_group_member(Elem, [members | Path], TrUserData) || Elem <- F7], ok;
       true -> mk_type_error({invalid_list_of, {msg, pb_group_member}}, F7, [members | Path])
    end,
    ok;
v_msg_pb_group_stanza(X, Path, _TrUserData) -> mk_type_error({expected_msg, pb_group_stanza}, X, Path).

-compile({nowarn_unused_function,v_msg_pb_group_chat/3}).
-dialyzer({nowarn_function,v_msg_pb_group_chat/3}).
v_msg_pb_group_chat(#pb_group_chat{gid = F1, name = F2, avatar_id = F3, sender_uid = F4, sender_name = F5, timestamp = F6, payload = F7}, Path, TrUserData) ->
    if F1 == undefined -> ok;
       true -> v_type_string(F1, [gid | Path], TrUserData)
    end,
    if F2 == undefined -> ok;
       true -> v_type_string(F2, [name | Path], TrUserData)
    end,
    if F3 == undefined -> ok;
       true -> v_type_string(F3, [avatar_id | Path], TrUserData)
    end,
    if F4 == undefined -> ok;
       true -> v_type_int64(F4, [sender_uid | Path], TrUserData)
    end,
    if F5 == undefined -> ok;
       true -> v_type_string(F5, [sender_name | Path], TrUserData)
    end,
    if F6 == undefined -> ok;
       true -> v_type_int64(F6, [timestamp | Path], TrUserData)
    end,
    if F7 == undefined -> ok;
       true -> v_type_bytes(F7, [payload | Path], TrUserData)
    end,
    ok;
v_msg_pb_group_chat(X, Path, _TrUserData) -> mk_type_error({expected_msg, pb_group_chat}, X, Path).

-compile({nowarn_unused_function,'v_enum_pb_group_member.Action'/3}).
-dialyzer({nowarn_function,'v_enum_pb_group_member.Action'/3}).
'v_enum_pb_group_member.Action'(add, _Path, _TrUserData) -> ok;
'v_enum_pb_group_member.Action'(remove, _Path, _TrUserData) -> ok;
'v_enum_pb_group_member.Action'(promote, _Path, _TrUserData) -> ok;
'v_enum_pb_group_member.Action'(demote, _Path, _TrUserData) -> ok;
'v_enum_pb_group_member.Action'(leave, _Path, _TrUserData) -> ok;
'v_enum_pb_group_member.Action'(V, Path, TrUserData) when is_integer(V) -> v_type_sint32(V, Path, TrUserData);
'v_enum_pb_group_member.Action'(X, Path, _TrUserData) -> mk_type_error({invalid_enum, 'pb_group_member.Action'}, X, Path).

-compile({nowarn_unused_function,'v_enum_pb_group_member.Type'/3}).
-dialyzer({nowarn_function,'v_enum_pb_group_member.Type'/3}).
'v_enum_pb_group_member.Type'(member, _Path, _TrUserData) -> ok;
'v_enum_pb_group_member.Type'(admin, _Path, _TrUserData) -> ok;
'v_enum_pb_group_member.Type'(V, Path, TrUserData) when is_integer(V) -> v_type_sint32(V, Path, TrUserData);
'v_enum_pb_group_member.Type'(X, Path, _TrUserData) -> mk_type_error({invalid_enum, 'pb_group_member.Type'}, X, Path).

-compile({nowarn_unused_function,'v_enum_pb_group_stanza.Action'/3}).
-dialyzer({nowarn_function,'v_enum_pb_group_stanza.Action'/3}).
'v_enum_pb_group_stanza.Action'(set, _Path, _TrUserData) -> ok;
'v_enum_pb_group_stanza.Action'(get, _Path, _TrUserData) -> ok;
'v_enum_pb_group_stanza.Action'(create, _Path, _TrUserData) -> ok;
'v_enum_pb_group_stanza.Action'(delete, _Path, _TrUserData) -> ok;
'v_enum_pb_group_stanza.Action'(leave, _Path, _TrUserData) -> ok;
'v_enum_pb_group_stanza.Action'(change_avatar, _Path, _TrUserData) -> ok;
'v_enum_pb_group_stanza.Action'(change_name, _Path, _TrUserData) -> ok;
'v_enum_pb_group_stanza.Action'(modify_admins, _Path, _TrUserData) -> ok;
'v_enum_pb_group_stanza.Action'(modify_members, _Path, _TrUserData) -> ok;
'v_enum_pb_group_stanza.Action'(auto_promote_admins, _Path, _TrUserData) -> ok;
'v_enum_pb_group_stanza.Action'(V, Path, TrUserData) when is_integer(V) -> v_type_sint32(V, Path, TrUserData);
'v_enum_pb_group_stanza.Action'(X, Path, _TrUserData) -> mk_type_error({invalid_enum, 'pb_group_stanza.Action'}, X, Path).

-compile({nowarn_unused_function,v_type_sint32/3}).
-dialyzer({nowarn_function,v_type_sint32/3}).
v_type_sint32(N, _Path, _TrUserData) when -2147483648 =< N, N =< 2147483647 -> ok;
v_type_sint32(N, Path, _TrUserData) when is_integer(N) -> mk_type_error({value_out_of_range, sint32, signed, 32}, N, Path);
v_type_sint32(X, Path, _TrUserData) -> mk_type_error({bad_integer, sint32, signed, 32}, X, Path).

-compile({nowarn_unused_function,v_type_int64/3}).
-dialyzer({nowarn_function,v_type_int64/3}).
v_type_int64(N, _Path, _TrUserData) when -9223372036854775808 =< N, N =< 9223372036854775807 -> ok;
v_type_int64(N, Path, _TrUserData) when is_integer(N) -> mk_type_error({value_out_of_range, int64, signed, 64}, N, Path);
v_type_int64(X, Path, _TrUserData) -> mk_type_error({bad_integer, int64, signed, 64}, X, Path).

-compile({nowarn_unused_function,v_type_string/3}).
-dialyzer({nowarn_function,v_type_string/3}).
v_type_string(S, Path, _TrUserData) when is_list(S); is_binary(S) ->
    try unicode:characters_to_binary(S) of
      B when is_binary(B) -> ok;
      {error, _, _} -> mk_type_error(bad_unicode_string, S, Path)
    catch
      error:badarg -> mk_type_error(bad_unicode_string, S, Path)
    end;
v_type_string(X, Path, _TrUserData) -> mk_type_error(bad_unicode_string, X, Path).

-compile({nowarn_unused_function,v_type_bytes/3}).
-dialyzer({nowarn_function,v_type_bytes/3}).
v_type_bytes(B, _Path, _TrUserData) when is_binary(B) -> ok;
v_type_bytes(B, _Path, _TrUserData) when is_list(B) -> ok;
v_type_bytes(X, Path, _TrUserData) -> mk_type_error(bad_binary_value, X, Path).

-compile({nowarn_unused_function,mk_type_error/3}).
-spec mk_type_error(_, _, list()) -> no_return().
mk_type_error(Error, ValueSeen, Path) -> Path2 = prettify_path(Path), erlang:error({gpb_type_error, {Error, [{value, ValueSeen}, {path, Path2}]}}).


-compile({nowarn_unused_function,prettify_path/1}).
-dialyzer({nowarn_function,prettify_path/1}).
prettify_path([]) -> top_level;
prettify_path(PathR) -> list_to_atom(lists:append(lists:join(".", lists:map(fun atom_to_list/1, lists:reverse(PathR))))).


-compile({nowarn_unused_function,id/2}).
-compile({inline,id/2}).
id(X, _TrUserData) -> X.

-compile({nowarn_unused_function,v_ok/3}).
-compile({inline,v_ok/3}).
v_ok(_Value, _Path, _TrUserData) -> ok.

-compile({nowarn_unused_function,m_overwrite/3}).
-compile({inline,m_overwrite/3}).
m_overwrite(_Prev, New, _TrUserData) -> New.

-compile({nowarn_unused_function,cons/3}).
-compile({inline,cons/3}).
cons(Elem, Acc, _TrUserData) -> [Elem | Acc].

-compile({nowarn_unused_function,lists_reverse/2}).
-compile({inline,lists_reverse/2}).
'lists_reverse'(L, _TrUserData) -> lists:reverse(L).
-compile({nowarn_unused_function,'erlang_++'/3}).
-compile({inline,'erlang_++'/3}).
'erlang_++'(A, B, _TrUserData) -> A ++ B.


get_msg_defs() ->
    [{{enum, 'pb_group_member.Action'}, [{add, 0}, {remove, 1}, {promote, 2}, {demote, 3}, {leave, 4}]}, {{enum, 'pb_group_member.Type'}, [{member, 1}, {admin, 2}]},
     {{enum, 'pb_group_stanza.Action'}, [{set, 0}, {get, 1}, {create, 2}, {delete, 3}, {leave, 4}, {change_avatar, 5}, {change_name, 6}, {modify_admins, 7}, {modify_members, 8}, {auto_promote_admins, 9}]},
     {{msg, pb_group_member},
      [#field{name = action, fnum = 1, rnum = 2, type = {enum, 'pb_group_member.Action'}, occurrence = optional, opts = []}, #field{name = uid, fnum = 2, rnum = 3, type = int64, occurrence = optional, opts = []},
       #field{name = type, fnum = 3, rnum = 4, type = {enum, 'pb_group_member.Type'}, occurrence = optional, opts = []}, #field{name = name, fnum = 4, rnum = 5, type = string, occurrence = optional, opts = []},
       #field{name = avatar_id, fnum = 5, rnum = 6, type = string, occurrence = optional, opts = []}, #field{name = result, fnum = 6, rnum = 7, type = string, occurrence = optional, opts = []},
       #field{name = reason, fnum = 7, rnum = 8, type = string, occurrence = optional, opts = []}]},
     {{msg, pb_group_stanza},
      [#field{name = action, fnum = 1, rnum = 2, type = {enum, 'pb_group_stanza.Action'}, occurrence = optional, opts = []}, #field{name = gid, fnum = 2, rnum = 3, type = string, occurrence = optional, opts = []},
       #field{name = name, fnum = 3, rnum = 4, type = string, occurrence = optional, opts = []}, #field{name = avatar_id, fnum = 4, rnum = 5, type = string, occurrence = optional, opts = []},
       #field{name = sender_uid, fnum = 5, rnum = 6, type = int64, occurrence = optional, opts = []}, #field{name = sender_name, fnum = 6, rnum = 7, type = string, occurrence = optional, opts = []},
       #field{name = members, fnum = 7, rnum = 8, type = {msg, pb_group_member}, occurrence = repeated, opts = []}]},
     {{msg, pb_group_chat},
      [#field{name = gid, fnum = 1, rnum = 2, type = string, occurrence = optional, opts = []}, #field{name = name, fnum = 2, rnum = 3, type = string, occurrence = optional, opts = []},
       #field{name = avatar_id, fnum = 3, rnum = 4, type = string, occurrence = optional, opts = []}, #field{name = sender_uid, fnum = 4, rnum = 5, type = int64, occurrence = optional, opts = []},
       #field{name = sender_name, fnum = 5, rnum = 6, type = string, occurrence = optional, opts = []}, #field{name = timestamp, fnum = 6, rnum = 7, type = int64, occurrence = optional, opts = []},
       #field{name = payload, fnum = 7, rnum = 8, type = bytes, occurrence = optional, opts = []}]}].


get_msg_names() -> [pb_group_member, pb_group_stanza, pb_group_chat].


get_group_names() -> [].


get_msg_or_group_names() -> [pb_group_member, pb_group_stanza, pb_group_chat].


get_enum_names() -> ['pb_group_member.Action', 'pb_group_member.Type', 'pb_group_stanza.Action'].


fetch_msg_def(MsgName) ->
    case find_msg_def(MsgName) of
      Fs when is_list(Fs) -> Fs;
      error -> erlang:error({no_such_msg, MsgName})
    end.


fetch_enum_def(EnumName) ->
    case find_enum_def(EnumName) of
      Es when is_list(Es) -> Es;
      error -> erlang:error({no_such_enum, EnumName})
    end.


find_msg_def(pb_group_member) ->
    [#field{name = action, fnum = 1, rnum = 2, type = {enum, 'pb_group_member.Action'}, occurrence = optional, opts = []}, #field{name = uid, fnum = 2, rnum = 3, type = int64, occurrence = optional, opts = []},
     #field{name = type, fnum = 3, rnum = 4, type = {enum, 'pb_group_member.Type'}, occurrence = optional, opts = []}, #field{name = name, fnum = 4, rnum = 5, type = string, occurrence = optional, opts = []},
     #field{name = avatar_id, fnum = 5, rnum = 6, type = string, occurrence = optional, opts = []}, #field{name = result, fnum = 6, rnum = 7, type = string, occurrence = optional, opts = []},
     #field{name = reason, fnum = 7, rnum = 8, type = string, occurrence = optional, opts = []}];
find_msg_def(pb_group_stanza) ->
    [#field{name = action, fnum = 1, rnum = 2, type = {enum, 'pb_group_stanza.Action'}, occurrence = optional, opts = []}, #field{name = gid, fnum = 2, rnum = 3, type = string, occurrence = optional, opts = []},
     #field{name = name, fnum = 3, rnum = 4, type = string, occurrence = optional, opts = []}, #field{name = avatar_id, fnum = 4, rnum = 5, type = string, occurrence = optional, opts = []},
     #field{name = sender_uid, fnum = 5, rnum = 6, type = int64, occurrence = optional, opts = []}, #field{name = sender_name, fnum = 6, rnum = 7, type = string, occurrence = optional, opts = []},
     #field{name = members, fnum = 7, rnum = 8, type = {msg, pb_group_member}, occurrence = repeated, opts = []}];
find_msg_def(pb_group_chat) ->
    [#field{name = gid, fnum = 1, rnum = 2, type = string, occurrence = optional, opts = []}, #field{name = name, fnum = 2, rnum = 3, type = string, occurrence = optional, opts = []},
     #field{name = avatar_id, fnum = 3, rnum = 4, type = string, occurrence = optional, opts = []}, #field{name = sender_uid, fnum = 4, rnum = 5, type = int64, occurrence = optional, opts = []},
     #field{name = sender_name, fnum = 5, rnum = 6, type = string, occurrence = optional, opts = []}, #field{name = timestamp, fnum = 6, rnum = 7, type = int64, occurrence = optional, opts = []},
     #field{name = payload, fnum = 7, rnum = 8, type = bytes, occurrence = optional, opts = []}];
find_msg_def(_) -> error.


find_enum_def('pb_group_member.Action') -> [{add, 0}, {remove, 1}, {promote, 2}, {demote, 3}, {leave, 4}];
find_enum_def('pb_group_member.Type') -> [{member, 1}, {admin, 2}];
find_enum_def('pb_group_stanza.Action') -> [{set, 0}, {get, 1}, {create, 2}, {delete, 3}, {leave, 4}, {change_avatar, 5}, {change_name, 6}, {modify_admins, 7}, {modify_members, 8}, {auto_promote_admins, 9}];
find_enum_def(_) -> error.


enum_symbol_by_value('pb_group_member.Action', Value) -> 'enum_symbol_by_value_pb_group_member.Action'(Value);
enum_symbol_by_value('pb_group_member.Type', Value) -> 'enum_symbol_by_value_pb_group_member.Type'(Value);
enum_symbol_by_value('pb_group_stanza.Action', Value) -> 'enum_symbol_by_value_pb_group_stanza.Action'(Value).


enum_value_by_symbol('pb_group_member.Action', Sym) -> 'enum_value_by_symbol_pb_group_member.Action'(Sym);
enum_value_by_symbol('pb_group_member.Type', Sym) -> 'enum_value_by_symbol_pb_group_member.Type'(Sym);
enum_value_by_symbol('pb_group_stanza.Action', Sym) -> 'enum_value_by_symbol_pb_group_stanza.Action'(Sym).


'enum_symbol_by_value_pb_group_member.Action'(0) -> add;
'enum_symbol_by_value_pb_group_member.Action'(1) -> remove;
'enum_symbol_by_value_pb_group_member.Action'(2) -> promote;
'enum_symbol_by_value_pb_group_member.Action'(3) -> demote;
'enum_symbol_by_value_pb_group_member.Action'(4) -> leave.


'enum_value_by_symbol_pb_group_member.Action'(add) -> 0;
'enum_value_by_symbol_pb_group_member.Action'(remove) -> 1;
'enum_value_by_symbol_pb_group_member.Action'(promote) -> 2;
'enum_value_by_symbol_pb_group_member.Action'(demote) -> 3;
'enum_value_by_symbol_pb_group_member.Action'(leave) -> 4.

'enum_symbol_by_value_pb_group_member.Type'(1) -> member;
'enum_symbol_by_value_pb_group_member.Type'(2) -> admin.


'enum_value_by_symbol_pb_group_member.Type'(member) -> 1;
'enum_value_by_symbol_pb_group_member.Type'(admin) -> 2.

'enum_symbol_by_value_pb_group_stanza.Action'(0) -> set;
'enum_symbol_by_value_pb_group_stanza.Action'(1) -> get;
'enum_symbol_by_value_pb_group_stanza.Action'(2) -> create;
'enum_symbol_by_value_pb_group_stanza.Action'(3) -> delete;
'enum_symbol_by_value_pb_group_stanza.Action'(4) -> leave;
'enum_symbol_by_value_pb_group_stanza.Action'(5) -> change_avatar;
'enum_symbol_by_value_pb_group_stanza.Action'(6) -> change_name;
'enum_symbol_by_value_pb_group_stanza.Action'(7) -> modify_admins;
'enum_symbol_by_value_pb_group_stanza.Action'(8) -> modify_members;
'enum_symbol_by_value_pb_group_stanza.Action'(9) -> auto_promote_admins.


'enum_value_by_symbol_pb_group_stanza.Action'(set) -> 0;
'enum_value_by_symbol_pb_group_stanza.Action'(get) -> 1;
'enum_value_by_symbol_pb_group_stanza.Action'(create) -> 2;
'enum_value_by_symbol_pb_group_stanza.Action'(delete) -> 3;
'enum_value_by_symbol_pb_group_stanza.Action'(leave) -> 4;
'enum_value_by_symbol_pb_group_stanza.Action'(change_avatar) -> 5;
'enum_value_by_symbol_pb_group_stanza.Action'(change_name) -> 6;
'enum_value_by_symbol_pb_group_stanza.Action'(modify_admins) -> 7;
'enum_value_by_symbol_pb_group_stanza.Action'(modify_members) -> 8;
'enum_value_by_symbol_pb_group_stanza.Action'(auto_promote_admins) -> 9.


get_service_names() -> [].


get_service_def(_) -> error.


get_rpc_names(_) -> error.


find_rpc_def(_, _) -> error.



-spec fetch_rpc_def(_, _) -> no_return().
fetch_rpc_def(ServiceName, RpcName) -> erlang:error({no_such_rpc, ServiceName, RpcName}).


%% Convert a a fully qualified (ie with package name) service name
%% as a binary to a service name as an atom.
-spec fqbin_to_service_name(_) -> no_return().
fqbin_to_service_name(X) -> error({gpb_error, {badservice, X}}).


%% Convert a service name as an atom to a fully qualified
%% (ie with package name) name as a binary.
-spec service_name_to_fqbin(_) -> no_return().
service_name_to_fqbin(X) -> error({gpb_error, {badservice, X}}).


%% Convert a a fully qualified (ie with package name) service name
%% and an rpc name, both as binaries to a service name and an rpc
%% name, as atoms.
-spec fqbins_to_service_and_rpc_name(_, _) -> no_return().
fqbins_to_service_and_rpc_name(S, R) -> error({gpb_error, {badservice_or_rpc, {S, R}}}).


%% Convert a service name and an rpc name, both as atoms,
%% to a fully qualified (ie with package name) service name and
%% an rpc name as binaries.
-spec service_and_rpc_name_to_fqbins(_, _) -> no_return().
service_and_rpc_name_to_fqbins(S, R) -> error({gpb_error, {badservice_or_rpc, {S, R}}}).


fqbin_to_msg_name(<<"group_member">>) -> pb_group_member;
fqbin_to_msg_name(<<"group_stanza">>) -> pb_group_stanza;
fqbin_to_msg_name(<<"group_chat">>) -> pb_group_chat;
fqbin_to_msg_name(E) -> error({gpb_error, {badmsg, E}}).


msg_name_to_fqbin(pb_group_member) -> <<"group_member">>;
msg_name_to_fqbin(pb_group_stanza) -> <<"group_stanza">>;
msg_name_to_fqbin(pb_group_chat) -> <<"group_chat">>;
msg_name_to_fqbin(E) -> error({gpb_error, {badmsg, E}}).


fqbin_to_enum_name(<<"group_member.Action">>) -> 'pb_group_member.Action';
fqbin_to_enum_name(<<"group_member.Type">>) -> 'pb_group_member.Type';
fqbin_to_enum_name(<<"group_stanza.Action">>) -> 'pb_group_stanza.Action';
fqbin_to_enum_name(E) -> error({gpb_error, {badenum, E}}).


enum_name_to_fqbin('pb_group_member.Action') -> <<"group_member.Action">>;
enum_name_to_fqbin('pb_group_member.Type') -> <<"group_member.Type">>;
enum_name_to_fqbin('pb_group_stanza.Action') -> <<"group_stanza.Action">>;
enum_name_to_fqbin(E) -> error({gpb_error, {badenum, E}}).


get_package_name() -> undefined.


%% Whether or not the message names
%% are prepended with package name or not.
uses_packages() -> false.


source_basename() -> "group_stanzas.proto".


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned with extension,
%% see get_all_proto_names/0 for a version that returns
%% the basenames sans extension
get_all_source_basenames() -> ["group_stanzas.proto"].


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned sans .proto extension,
%% to make it easier to use them with the various get_xyz_containment
%% functions.
get_all_proto_names() -> ["group_stanzas"].


get_msg_containment("group_stanzas") -> [pb_group_chat, pb_group_member, pb_group_stanza];
get_msg_containment(P) -> error({gpb_error, {badproto, P}}).


get_pkg_containment("group_stanzas") -> undefined;
get_pkg_containment(P) -> error({gpb_error, {badproto, P}}).


get_service_containment("group_stanzas") -> [];
get_service_containment(P) -> error({gpb_error, {badproto, P}}).


get_rpc_containment("group_stanzas") -> [];
get_rpc_containment(P) -> error({gpb_error, {badproto, P}}).


get_enum_containment("group_stanzas") -> ['pb_group_member.Action', 'pb_group_member.Type', 'pb_group_stanza.Action'];
get_enum_containment(P) -> error({gpb_error, {badproto, P}}).


get_proto_by_msg_name_as_fqbin(<<"group_stanza">>) -> "group_stanzas";
get_proto_by_msg_name_as_fqbin(<<"group_member">>) -> "group_stanzas";
get_proto_by_msg_name_as_fqbin(<<"group_chat">>) -> "group_stanzas";
get_proto_by_msg_name_as_fqbin(E) -> error({gpb_error, {badmsg, E}}).


-spec get_proto_by_service_name_as_fqbin(_) -> no_return().
get_proto_by_service_name_as_fqbin(E) -> error({gpb_error, {badservice, E}}).


get_proto_by_enum_name_as_fqbin(<<"group_member.Type">>) -> "group_stanzas";
get_proto_by_enum_name_as_fqbin(<<"group_stanza.Action">>) -> "group_stanzas";
get_proto_by_enum_name_as_fqbin(<<"group_member.Action">>) -> "group_stanzas";
get_proto_by_enum_name_as_fqbin(E) -> error({gpb_error, {badenum, E}}).


-spec get_protos_by_pkg_name_as_fqbin(_) -> no_return().
get_protos_by_pkg_name_as_fqbin(E) -> error({gpb_error, {badpkg, E}}).



gpb_version_as_string() ->
    "4.13.0".

gpb_version_as_list() ->
    [4,13,0].
