%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.13.0
-module(push).

-export([encode_msg/1, encode_msg/2, encode_msg/3]).
-export([decode_msg/2, decode_msg/3]).
-export([merge_msgs/2, merge_msgs/3, merge_msgs/4]).
-export([verify_msg/1, verify_msg/2, verify_msg/3]).
-export([get_msg_defs/0]).
-export([get_msg_names/0]).
-export([get_group_names/0]).
-export([get_msg_or_group_names/0]).
-export([get_enum_names/0]).
-export([find_msg_def/1, fetch_msg_def/1]).
-export([find_enum_def/1, fetch_enum_def/1]).
-export([enum_symbol_by_value/2, enum_value_by_symbol/2]).
-export(['enum_symbol_by_value_pb_push_token.Os'/1, 'enum_value_by_symbol_pb_push_token.Os'/1]).
-export([get_service_names/0]).
-export([get_service_def/1]).
-export([get_rpc_names/1]).
-export([find_rpc_def/2, fetch_rpc_def/2]).
-export([fqbin_to_service_name/1]).
-export([service_name_to_fqbin/1]).
-export([fqbins_to_service_and_rpc_name/2]).
-export([service_and_rpc_name_to_fqbins/2]).
-export([fqbin_to_msg_name/1]).
-export([msg_name_to_fqbin/1]).
-export([fqbin_to_enum_name/1]).
-export([enum_name_to_fqbin/1]).
-export([get_package_name/0]).
-export([uses_packages/0]).
-export([source_basename/0]).
-export([get_all_source_basenames/0]).
-export([get_all_proto_names/0]).
-export([get_msg_containment/1]).
-export([get_pkg_containment/1]).
-export([get_service_containment/1]).
-export([get_rpc_containment/1]).
-export([get_enum_containment/1]).
-export([get_proto_by_msg_name_as_fqbin/1]).
-export([get_proto_by_service_name_as_fqbin/1]).
-export([get_proto_by_enum_name_as_fqbin/1]).
-export([get_protos_by_pkg_name_as_fqbin/1]).
-export([gpb_version_as_string/0, gpb_version_as_list/0]).

-include("push.hrl").
-include("gpb.hrl").

%% enumerated types
-type 'pb_push_token.Os'() :: android | ios | ios_dev.
-export_type(['pb_push_token.Os'/0]).

%% message types
-type pb_push_token() :: #pb_push_token{}.

-type pb_push_register() :: #pb_push_register{}.

-export_type(['pb_push_token'/0, 'pb_push_register'/0]).

-spec encode_msg(#pb_push_token{} | #pb_push_register{}) -> binary().
encode_msg(Msg) when tuple_size(Msg) >= 1 -> encode_msg(Msg, element(1, Msg), []).

-spec encode_msg(#pb_push_token{} | #pb_push_register{}, atom() | list()) -> binary().
encode_msg(Msg, MsgName) when is_atom(MsgName) -> encode_msg(Msg, MsgName, []);
encode_msg(Msg, Opts) when tuple_size(Msg) >= 1, is_list(Opts) -> encode_msg(Msg, element(1, Msg), Opts).

-spec encode_msg(#pb_push_token{} | #pb_push_register{}, atom(), list()) -> binary().
encode_msg(Msg, MsgName, Opts) ->
    case proplists:get_bool(verify, Opts) of
      true -> verify_msg(Msg, MsgName, Opts);
      false -> ok
    end,
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
      pb_push_token -> encode_msg_pb_push_token(id(Msg, TrUserData), TrUserData);
      pb_push_register -> encode_msg_pb_push_register(id(Msg, TrUserData), TrUserData)
    end.


encode_msg_pb_push_token(Msg, TrUserData) -> encode_msg_pb_push_token(Msg, <<>>, TrUserData).


encode_msg_pb_push_token(#pb_push_token{os = F1, token = F2}, Bin, TrUserData) ->
    B1 = if F1 == undefined -> Bin;
	    true ->
		begin
		  TrF1 = id(F1, TrUserData),
		  if TrF1 =:= android; TrF1 =:= 0 -> Bin;
		     true -> 'e_enum_pb_push_token.Os'(TrF1, <<Bin/binary, 8>>, TrUserData)
		  end
		end
	 end,
    if F2 == undefined -> B1;
       true ->
	   begin
	     TrF2 = id(F2, TrUserData),
	     case is_empty_string(TrF2) of
	       true -> B1;
	       false -> e_type_string(TrF2, <<B1/binary, 18>>, TrUserData)
	     end
	   end
    end.

encode_msg_pb_push_register(Msg, TrUserData) -> encode_msg_pb_push_register(Msg, <<>>, TrUserData).


encode_msg_pb_push_register(#pb_push_register{push_token = F1}, Bin, TrUserData) ->
    if F1 == undefined -> Bin;
       true ->
	   begin
	     TrF1 = id(F1, TrUserData),
	     if TrF1 =:= undefined -> Bin;
		true -> e_mfield_pb_push_register_push_token(TrF1, <<Bin/binary, 10>>, TrUserData)
	     end
	   end
    end.

e_mfield_pb_push_register_push_token(Msg, Bin, TrUserData) -> SubBin = encode_msg_pb_push_token(Msg, <<>>, TrUserData), Bin2 = e_varint(byte_size(SubBin), Bin), <<Bin2/binary, SubBin/binary>>.

'e_enum_pb_push_token.Os'(android, Bin, _TrUserData) -> <<Bin/binary, 0>>;
'e_enum_pb_push_token.Os'(ios, Bin, _TrUserData) -> <<Bin/binary, 1>>;
'e_enum_pb_push_token.Os'(ios_dev, Bin, _TrUserData) -> <<Bin/binary, 2>>;
'e_enum_pb_push_token.Os'(V, Bin, _TrUserData) -> e_varint(V, Bin).

-compile({nowarn_unused_function,e_type_sint/3}).
e_type_sint(Value, Bin, _TrUserData) when Value >= 0 -> e_varint(Value * 2, Bin);
e_type_sint(Value, Bin, _TrUserData) -> e_varint(Value * -2 - 1, Bin).

-compile({nowarn_unused_function,e_type_int32/3}).
e_type_int32(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int32(Value, Bin, _TrUserData) -> <<N:64/unsigned-native>> = <<Value:64/signed-native>>, e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_int64/3}).
e_type_int64(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int64(Value, Bin, _TrUserData) -> <<N:64/unsigned-native>> = <<Value:64/signed-native>>, e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_bool/3}).
e_type_bool(true, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(false, Bin, _TrUserData) -> <<Bin/binary, 0>>;
e_type_bool(1, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(0, Bin, _TrUserData) -> <<Bin/binary, 0>>.

-compile({nowarn_unused_function,e_type_string/3}).
e_type_string(S, Bin, _TrUserData) -> Utf8 = unicode:characters_to_binary(S), Bin2 = e_varint(byte_size(Utf8), Bin), <<Bin2/binary, Utf8/binary>>.

-compile({nowarn_unused_function,e_type_bytes/3}).
e_type_bytes(Bytes, Bin, _TrUserData) when is_binary(Bytes) -> Bin2 = e_varint(byte_size(Bytes), Bin), <<Bin2/binary, Bytes/binary>>;
e_type_bytes(Bytes, Bin, _TrUserData) when is_list(Bytes) -> BytesBin = iolist_to_binary(Bytes), Bin2 = e_varint(byte_size(BytesBin), Bin), <<Bin2/binary, BytesBin/binary>>.

-compile({nowarn_unused_function,e_type_fixed32/3}).
e_type_fixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little>>.

-compile({nowarn_unused_function,e_type_sfixed32/3}).
e_type_sfixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little-signed>>.

-compile({nowarn_unused_function,e_type_fixed64/3}).
e_type_fixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little>>.

-compile({nowarn_unused_function,e_type_sfixed64/3}).
e_type_sfixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little-signed>>.

-compile({nowarn_unused_function,e_type_float/3}).
e_type_float(V, Bin, _) when is_number(V) -> <<Bin/binary, V:32/little-float>>;
e_type_float(infinity, Bin, _) -> <<Bin/binary, 0:16, 128, 127>>;
e_type_float('-infinity', Bin, _) -> <<Bin/binary, 0:16, 128, 255>>;
e_type_float(nan, Bin, _) -> <<Bin/binary, 0:16, 192, 127>>.

-compile({nowarn_unused_function,e_type_double/3}).
e_type_double(V, Bin, _) when is_number(V) -> <<Bin/binary, V:64/little-float>>;
e_type_double(infinity, Bin, _) -> <<Bin/binary, 0:48, 240, 127>>;
e_type_double('-infinity', Bin, _) -> <<Bin/binary, 0:48, 240, 255>>;
e_type_double(nan, Bin, _) -> <<Bin/binary, 0:48, 248, 127>>.

-compile({nowarn_unused_function,e_varint/3}).
e_varint(N, Bin, _TrUserData) -> e_varint(N, Bin).

-compile({nowarn_unused_function,e_varint/2}).
e_varint(N, Bin) when N =< 127 -> <<Bin/binary, N>>;
e_varint(N, Bin) -> Bin2 = <<Bin/binary, (N band 127 bor 128)>>, e_varint(N bsr 7, Bin2).

is_empty_string("") -> true;
is_empty_string(<<>>) -> true;
is_empty_string(L) when is_list(L) -> not string_has_chars(L);
is_empty_string(B) when is_binary(B) -> false.

string_has_chars([C | _]) when is_integer(C) -> true;
string_has_chars([H | T]) ->
    case string_has_chars(H) of
      true -> true;
      false -> string_has_chars(T)
    end;
string_has_chars(B) when is_binary(B), byte_size(B) =/= 0 -> true;
string_has_chars(C) when is_integer(C) -> true;
string_has_chars(<<>>) -> false;
string_has_chars([]) -> false.


decode_msg(Bin, MsgName) when is_binary(Bin) -> decode_msg(Bin, MsgName, []).

decode_msg(Bin, MsgName, Opts) when is_binary(Bin) -> TrUserData = proplists:get_value(user_data, Opts), decode_msg_1_catch(Bin, MsgName, TrUserData).

-ifdef('OTP_RELEASE').
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch Class:Reason:StackTrace -> error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-else.
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch Class:Reason ->
        StackTrace = erlang:get_stacktrace(),
        error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-endif.

decode_msg_2_doit(pb_push_token, Bin, TrUserData) -> id(decode_msg_pb_push_token(Bin, TrUserData), TrUserData);
decode_msg_2_doit(pb_push_register, Bin, TrUserData) -> id(decode_msg_pb_push_register(Bin, TrUserData), TrUserData).



decode_msg_pb_push_token(Bin, TrUserData) -> dfp_read_field_def_pb_push_token(Bin, 0, 0, id(android, TrUserData), id(<<>>, TrUserData), TrUserData).

dfp_read_field_def_pb_push_token(<<8, Rest/binary>>, Z1, Z2, F@_1, F@_2, TrUserData) -> d_field_pb_push_token_os(Rest, Z1, Z2, F@_1, F@_2, TrUserData);
dfp_read_field_def_pb_push_token(<<18, Rest/binary>>, Z1, Z2, F@_1, F@_2, TrUserData) -> d_field_pb_push_token_token(Rest, Z1, Z2, F@_1, F@_2, TrUserData);
dfp_read_field_def_pb_push_token(<<>>, 0, 0, F@_1, F@_2, _) -> #pb_push_token{os = F@_1, token = F@_2};
dfp_read_field_def_pb_push_token(Other, Z1, Z2, F@_1, F@_2, TrUserData) -> dg_read_field_def_pb_push_token(Other, Z1, Z2, F@_1, F@_2, TrUserData).

dg_read_field_def_pb_push_token(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, TrUserData) when N < 32 - 7 -> dg_read_field_def_pb_push_token(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, TrUserData);
dg_read_field_def_pb_push_token(<<0:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      8 -> d_field_pb_push_token_os(Rest, 0, 0, F@_1, F@_2, TrUserData);
      18 -> d_field_pb_push_token_token(Rest, 0, 0, F@_1, F@_2, TrUserData);
      _ ->
	  case Key band 7 of
	    0 -> skip_varint_pb_push_token(Rest, 0, 0, F@_1, F@_2, TrUserData);
	    1 -> skip_64_pb_push_token(Rest, 0, 0, F@_1, F@_2, TrUserData);
	    2 -> skip_length_delimited_pb_push_token(Rest, 0, 0, F@_1, F@_2, TrUserData);
	    3 -> skip_group_pb_push_token(Rest, Key bsr 3, 0, F@_1, F@_2, TrUserData);
	    5 -> skip_32_pb_push_token(Rest, 0, 0, F@_1, F@_2, TrUserData)
	  end
    end;
dg_read_field_def_pb_push_token(<<>>, 0, 0, F@_1, F@_2, _) -> #pb_push_token{os = F@_1, token = F@_2}.

d_field_pb_push_token_os(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, TrUserData) when N < 57 -> d_field_pb_push_token_os(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, TrUserData);
d_field_pb_push_token_os(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_2, TrUserData) ->
    {NewFValue, RestF} = {id('d_enum_pb_push_token.Os'(begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end), TrUserData), Rest}, dfp_read_field_def_pb_push_token(RestF, 0, 0, NewFValue, F@_2, TrUserData).

d_field_pb_push_token_token(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, TrUserData) when N < 57 -> d_field_pb_push_token_token(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, TrUserData);
d_field_pb_push_token_token(<<0:1, X:7, Rest/binary>>, N, Acc, F@_1, _, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, {id(binary:copy(Bytes), TrUserData), Rest2} end, dfp_read_field_def_pb_push_token(RestF, 0, 0, F@_1, NewFValue, TrUserData).

skip_varint_pb_push_token(<<1:1, _:7, Rest/binary>>, Z1, Z2, F@_1, F@_2, TrUserData) -> skip_varint_pb_push_token(Rest, Z1, Z2, F@_1, F@_2, TrUserData);
skip_varint_pb_push_token(<<0:1, _:7, Rest/binary>>, Z1, Z2, F@_1, F@_2, TrUserData) -> dfp_read_field_def_pb_push_token(Rest, Z1, Z2, F@_1, F@_2, TrUserData).

skip_length_delimited_pb_push_token(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, TrUserData) when N < 57 -> skip_length_delimited_pb_push_token(Rest, N + 7, X bsl N + Acc, F@_1, F@_2, TrUserData);
skip_length_delimited_pb_push_token(<<0:1, X:7, Rest/binary>>, N, Acc, F@_1, F@_2, TrUserData) -> Length = X bsl N + Acc, <<_:Length/binary, Rest2/binary>> = Rest, dfp_read_field_def_pb_push_token(Rest2, 0, 0, F@_1, F@_2, TrUserData).

skip_group_pb_push_token(Bin, FNum, Z2, F@_1, F@_2, TrUserData) -> {_, Rest} = read_group(Bin, FNum), dfp_read_field_def_pb_push_token(Rest, 0, Z2, F@_1, F@_2, TrUserData).

skip_32_pb_push_token(<<_:32, Rest/binary>>, Z1, Z2, F@_1, F@_2, TrUserData) -> dfp_read_field_def_pb_push_token(Rest, Z1, Z2, F@_1, F@_2, TrUserData).

skip_64_pb_push_token(<<_:64, Rest/binary>>, Z1, Z2, F@_1, F@_2, TrUserData) -> dfp_read_field_def_pb_push_token(Rest, Z1, Z2, F@_1, F@_2, TrUserData).

decode_msg_pb_push_register(Bin, TrUserData) -> dfp_read_field_def_pb_push_register(Bin, 0, 0, id(undefined, TrUserData), TrUserData).

dfp_read_field_def_pb_push_register(<<10, Rest/binary>>, Z1, Z2, F@_1, TrUserData) -> d_field_pb_push_register_push_token(Rest, Z1, Z2, F@_1, TrUserData);
dfp_read_field_def_pb_push_register(<<>>, 0, 0, F@_1, _) -> #pb_push_register{push_token = F@_1};
dfp_read_field_def_pb_push_register(Other, Z1, Z2, F@_1, TrUserData) -> dg_read_field_def_pb_push_register(Other, Z1, Z2, F@_1, TrUserData).

dg_read_field_def_pb_push_register(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, TrUserData) when N < 32 - 7 -> dg_read_field_def_pb_push_register(Rest, N + 7, X bsl N + Acc, F@_1, TrUserData);
dg_read_field_def_pb_push_register(<<0:1, X:7, Rest/binary>>, N, Acc, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      10 -> d_field_pb_push_register_push_token(Rest, 0, 0, F@_1, TrUserData);
      _ ->
	  case Key band 7 of
	    0 -> skip_varint_pb_push_register(Rest, 0, 0, F@_1, TrUserData);
	    1 -> skip_64_pb_push_register(Rest, 0, 0, F@_1, TrUserData);
	    2 -> skip_length_delimited_pb_push_register(Rest, 0, 0, F@_1, TrUserData);
	    3 -> skip_group_pb_push_register(Rest, Key bsr 3, 0, F@_1, TrUserData);
	    5 -> skip_32_pb_push_register(Rest, 0, 0, F@_1, TrUserData)
	  end
    end;
dg_read_field_def_pb_push_register(<<>>, 0, 0, F@_1, _) -> #pb_push_register{push_token = F@_1}.

d_field_pb_push_register_push_token(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, TrUserData) when N < 57 -> d_field_pb_push_register_push_token(Rest, N + 7, X bsl N + Acc, F@_1, TrUserData);
d_field_pb_push_register_push_token(<<0:1, X:7, Rest/binary>>, N, Acc, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_pb_push_token(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_pb_push_register(RestF, 0, 0,
					if Prev == undefined -> NewFValue;
					   true -> merge_msg_pb_push_token(Prev, NewFValue, TrUserData)
					end,
					TrUserData).

skip_varint_pb_push_register(<<1:1, _:7, Rest/binary>>, Z1, Z2, F@_1, TrUserData) -> skip_varint_pb_push_register(Rest, Z1, Z2, F@_1, TrUserData);
skip_varint_pb_push_register(<<0:1, _:7, Rest/binary>>, Z1, Z2, F@_1, TrUserData) -> dfp_read_field_def_pb_push_register(Rest, Z1, Z2, F@_1, TrUserData).

skip_length_delimited_pb_push_register(<<1:1, X:7, Rest/binary>>, N, Acc, F@_1, TrUserData) when N < 57 -> skip_length_delimited_pb_push_register(Rest, N + 7, X bsl N + Acc, F@_1, TrUserData);
skip_length_delimited_pb_push_register(<<0:1, X:7, Rest/binary>>, N, Acc, F@_1, TrUserData) -> Length = X bsl N + Acc, <<_:Length/binary, Rest2/binary>> = Rest, dfp_read_field_def_pb_push_register(Rest2, 0, 0, F@_1, TrUserData).

skip_group_pb_push_register(Bin, FNum, Z2, F@_1, TrUserData) -> {_, Rest} = read_group(Bin, FNum), dfp_read_field_def_pb_push_register(Rest, 0, Z2, F@_1, TrUserData).

skip_32_pb_push_register(<<_:32, Rest/binary>>, Z1, Z2, F@_1, TrUserData) -> dfp_read_field_def_pb_push_register(Rest, Z1, Z2, F@_1, TrUserData).

skip_64_pb_push_register(<<_:64, Rest/binary>>, Z1, Z2, F@_1, TrUserData) -> dfp_read_field_def_pb_push_register(Rest, Z1, Z2, F@_1, TrUserData).

'd_enum_pb_push_token.Os'(0) -> android;
'd_enum_pb_push_token.Os'(1) -> ios;
'd_enum_pb_push_token.Os'(2) -> ios_dev;
'd_enum_pb_push_token.Os'(V) -> V.

read_group(Bin, FieldNum) ->
    {NumBytes, EndTagLen} = read_gr_b(Bin, 0, 0, 0, 0, FieldNum),
    <<Group:NumBytes/binary, _:EndTagLen/binary, Rest/binary>> = Bin,
    {Group, Rest}.

%% Like skipping over fields, but record the total length,
%% Each field is <(FieldNum bsl 3) bor FieldType> ++ <FieldValue>
%% Record the length because varints may be non-optimally encoded.
%%
%% Groups can be nested, but assume the same FieldNum cannot be nested
%% because group field numbers are shared with the rest of the fields
%% numbers. Thus we can search just for an group-end with the same
%% field number.
%%
%% (The only time the same group field number could occur would
%% be in a nested sub message, but then it would be inside a
%% length-delimited entry, which we skip-read by length.)
read_gr_b(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen, FieldNum)
  when N < (32-7) ->
    read_gr_b(Tl, N+7, X bsl N + Acc, NumBytes, TagLen+1, FieldNum);
read_gr_b(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen,
          FieldNum) ->
    Key = X bsl N + Acc,
    TagLen1 = TagLen + 1,
    case {Key bsr 3, Key band 7} of
        {FieldNum, 4} -> % 4 = group_end
            {NumBytes, TagLen1};
        {_, 0} -> % 0 = varint
            read_gr_vi(Tl, 0, NumBytes + TagLen1, FieldNum);
        {_, 1} -> % 1 = bits64
            <<_:64, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 8, 0, FieldNum);
        {_, 2} -> % 2 = length_delimited
            read_gr_ld(Tl, 0, 0, NumBytes + TagLen1, FieldNum);
        {_, 3} -> % 3 = group_start
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 4} -> % 4 = group_end
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 5} -> % 5 = bits32
            <<_:32, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 4, 0, FieldNum)
    end.

read_gr_vi(<<1:1, _:7, Tl/binary>>, N, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_vi(Tl, N+7, NumBytes+1, FieldNum);
read_gr_vi(<<0:1, _:7, Tl/binary>>, _, NumBytes, FieldNum) ->
    read_gr_b(Tl, 0, 0, NumBytes+1, 0, FieldNum).

read_gr_ld(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_ld(Tl, N+7, X bsl N + Acc, NumBytes+1, FieldNum);
read_gr_ld(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum) ->
    Len = X bsl N + Acc,
    NumBytes1 = NumBytes + 1,
    <<_:Len/binary, Tl2/binary>> = Tl,
    read_gr_b(Tl2, 0, 0, NumBytes1 + Len, 0, FieldNum).

merge_msgs(Prev, New) when element(1, Prev) =:= element(1, New) -> merge_msgs(Prev, New, element(1, Prev), []).

merge_msgs(Prev, New, MsgName) when is_atom(MsgName) -> merge_msgs(Prev, New, MsgName, []);
merge_msgs(Prev, New, Opts) when element(1, Prev) =:= element(1, New), is_list(Opts) -> merge_msgs(Prev, New, element(1, Prev), Opts).

merge_msgs(Prev, New, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
      pb_push_token -> merge_msg_pb_push_token(Prev, New, TrUserData);
      pb_push_register -> merge_msg_pb_push_register(Prev, New, TrUserData)
    end.

-compile({nowarn_unused_function,merge_msg_pb_push_token/3}).
merge_msg_pb_push_token(#pb_push_token{os = PFos, token = PFtoken}, #pb_push_token{os = NFos, token = NFtoken}, _) ->
    #pb_push_token{os =
		       if NFos =:= undefined -> PFos;
			  true -> NFos
		       end,
		   token =
		       if NFtoken =:= undefined -> PFtoken;
			  true -> NFtoken
		       end}.

-compile({nowarn_unused_function,merge_msg_pb_push_register/3}).
merge_msg_pb_push_register(#pb_push_register{push_token = PFpush_token}, #pb_push_register{push_token = NFpush_token}, TrUserData) ->
    #pb_push_register{push_token =
			  if PFpush_token /= undefined, NFpush_token /= undefined -> merge_msg_pb_push_token(PFpush_token, NFpush_token, TrUserData);
			     PFpush_token == undefined -> NFpush_token;
			     NFpush_token == undefined -> PFpush_token
			  end}.


verify_msg(Msg) when tuple_size(Msg) >= 1 -> verify_msg(Msg, element(1, Msg), []);
verify_msg(X) -> mk_type_error(not_a_known_message, X, []).

verify_msg(Msg, MsgName) when is_atom(MsgName) -> verify_msg(Msg, MsgName, []);
verify_msg(Msg, Opts) when tuple_size(Msg) >= 1 -> verify_msg(Msg, element(1, Msg), Opts);
verify_msg(X, _Opts) -> mk_type_error(not_a_known_message, X, []).

verify_msg(Msg, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
      pb_push_token -> v_msg_pb_push_token(Msg, [MsgName], TrUserData);
      pb_push_register -> v_msg_pb_push_register(Msg, [MsgName], TrUserData);
      _ -> mk_type_error(not_a_known_message, Msg, [])
    end.


-compile({nowarn_unused_function,v_msg_pb_push_token/3}).
-dialyzer({nowarn_function,v_msg_pb_push_token/3}).
v_msg_pb_push_token(#pb_push_token{os = F1, token = F2}, Path, TrUserData) ->
    if F1 == undefined -> ok;
       true -> 'v_enum_pb_push_token.Os'(F1, [os | Path], TrUserData)
    end,
    if F2 == undefined -> ok;
       true -> v_type_string(F2, [token | Path], TrUserData)
    end,
    ok;
v_msg_pb_push_token(X, Path, _TrUserData) -> mk_type_error({expected_msg, pb_push_token}, X, Path).

-compile({nowarn_unused_function,v_msg_pb_push_register/3}).
-dialyzer({nowarn_function,v_msg_pb_push_register/3}).
v_msg_pb_push_register(#pb_push_register{push_token = F1}, Path, TrUserData) ->
    if F1 == undefined -> ok;
       true -> v_msg_pb_push_token(F1, [push_token | Path], TrUserData)
    end,
    ok;
v_msg_pb_push_register(X, Path, _TrUserData) -> mk_type_error({expected_msg, pb_push_register}, X, Path).

-compile({nowarn_unused_function,'v_enum_pb_push_token.Os'/3}).
-dialyzer({nowarn_function,'v_enum_pb_push_token.Os'/3}).
'v_enum_pb_push_token.Os'(android, _Path, _TrUserData) -> ok;
'v_enum_pb_push_token.Os'(ios, _Path, _TrUserData) -> ok;
'v_enum_pb_push_token.Os'(ios_dev, _Path, _TrUserData) -> ok;
'v_enum_pb_push_token.Os'(V, Path, TrUserData) when is_integer(V) -> v_type_sint32(V, Path, TrUserData);
'v_enum_pb_push_token.Os'(X, Path, _TrUserData) -> mk_type_error({invalid_enum, 'pb_push_token.Os'}, X, Path).

-compile({nowarn_unused_function,v_type_sint32/3}).
-dialyzer({nowarn_function,v_type_sint32/3}).
v_type_sint32(N, _Path, _TrUserData) when -2147483648 =< N, N =< 2147483647 -> ok;
v_type_sint32(N, Path, _TrUserData) when is_integer(N) -> mk_type_error({value_out_of_range, sint32, signed, 32}, N, Path);
v_type_sint32(X, Path, _TrUserData) -> mk_type_error({bad_integer, sint32, signed, 32}, X, Path).

-compile({nowarn_unused_function,v_type_string/3}).
-dialyzer({nowarn_function,v_type_string/3}).
v_type_string(S, Path, _TrUserData) when is_list(S); is_binary(S) ->
    try unicode:characters_to_binary(S) of
      B when is_binary(B) -> ok;
      {error, _, _} -> mk_type_error(bad_unicode_string, S, Path)
    catch
      error:badarg -> mk_type_error(bad_unicode_string, S, Path)
    end;
v_type_string(X, Path, _TrUserData) -> mk_type_error(bad_unicode_string, X, Path).

-compile({nowarn_unused_function,mk_type_error/3}).
-spec mk_type_error(_, _, list()) -> no_return().
mk_type_error(Error, ValueSeen, Path) -> Path2 = prettify_path(Path), erlang:error({gpb_type_error, {Error, [{value, ValueSeen}, {path, Path2}]}}).


-compile({nowarn_unused_function,prettify_path/1}).
-dialyzer({nowarn_function,prettify_path/1}).
prettify_path([]) -> top_level;
prettify_path(PathR) -> list_to_atom(lists:append(lists:join(".", lists:map(fun atom_to_list/1, lists:reverse(PathR))))).


-compile({nowarn_unused_function,id/2}).
-compile({inline,id/2}).
id(X, _TrUserData) -> X.

-compile({nowarn_unused_function,v_ok/3}).
-compile({inline,v_ok/3}).
v_ok(_Value, _Path, _TrUserData) -> ok.

-compile({nowarn_unused_function,m_overwrite/3}).
-compile({inline,m_overwrite/3}).
m_overwrite(_Prev, New, _TrUserData) -> New.

-compile({nowarn_unused_function,cons/3}).
-compile({inline,cons/3}).
cons(Elem, Acc, _TrUserData) -> [Elem | Acc].

-compile({nowarn_unused_function,lists_reverse/2}).
-compile({inline,lists_reverse/2}).
'lists_reverse'(L, _TrUserData) -> lists:reverse(L).
-compile({nowarn_unused_function,'erlang_++'/3}).
-compile({inline,'erlang_++'/3}).
'erlang_++'(A, B, _TrUserData) -> A ++ B.


get_msg_defs() ->
    [{{enum, 'pb_push_token.Os'}, [{android, 0}, {ios, 1}, {ios_dev, 2}]},
     {{msg, pb_push_token}, [#field{name = os, fnum = 1, rnum = 2, type = {enum, 'pb_push_token.Os'}, occurrence = optional, opts = []}, #field{name = token, fnum = 2, rnum = 3, type = string, occurrence = optional, opts = []}]},
     {{msg, pb_push_register}, [#field{name = push_token, fnum = 1, rnum = 2, type = {msg, pb_push_token}, occurrence = optional, opts = []}]}].


get_msg_names() -> [pb_push_token, pb_push_register].


get_group_names() -> [].


get_msg_or_group_names() -> [pb_push_token, pb_push_register].


get_enum_names() -> ['pb_push_token.Os'].


fetch_msg_def(MsgName) ->
    case find_msg_def(MsgName) of
      Fs when is_list(Fs) -> Fs;
      error -> erlang:error({no_such_msg, MsgName})
    end.


fetch_enum_def(EnumName) ->
    case find_enum_def(EnumName) of
      Es when is_list(Es) -> Es;
      error -> erlang:error({no_such_enum, EnumName})
    end.


find_msg_def(pb_push_token) -> [#field{name = os, fnum = 1, rnum = 2, type = {enum, 'pb_push_token.Os'}, occurrence = optional, opts = []}, #field{name = token, fnum = 2, rnum = 3, type = string, occurrence = optional, opts = []}];
find_msg_def(pb_push_register) -> [#field{name = push_token, fnum = 1, rnum = 2, type = {msg, pb_push_token}, occurrence = optional, opts = []}];
find_msg_def(_) -> error.


find_enum_def('pb_push_token.Os') -> [{android, 0}, {ios, 1}, {ios_dev, 2}];
find_enum_def(_) -> error.


enum_symbol_by_value('pb_push_token.Os', Value) -> 'enum_symbol_by_value_pb_push_token.Os'(Value).


enum_value_by_symbol('pb_push_token.Os', Sym) -> 'enum_value_by_symbol_pb_push_token.Os'(Sym).


'enum_symbol_by_value_pb_push_token.Os'(0) -> android;
'enum_symbol_by_value_pb_push_token.Os'(1) -> ios;
'enum_symbol_by_value_pb_push_token.Os'(2) -> ios_dev.


'enum_value_by_symbol_pb_push_token.Os'(android) -> 0;
'enum_value_by_symbol_pb_push_token.Os'(ios) -> 1;
'enum_value_by_symbol_pb_push_token.Os'(ios_dev) -> 2.


get_service_names() -> [].


get_service_def(_) -> error.


get_rpc_names(_) -> error.


find_rpc_def(_, _) -> error.



-spec fetch_rpc_def(_, _) -> no_return().
fetch_rpc_def(ServiceName, RpcName) -> erlang:error({no_such_rpc, ServiceName, RpcName}).


%% Convert a a fully qualified (ie with package name) service name
%% as a binary to a service name as an atom.
-spec fqbin_to_service_name(_) -> no_return().
fqbin_to_service_name(X) -> error({gpb_error, {badservice, X}}).


%% Convert a service name as an atom to a fully qualified
%% (ie with package name) name as a binary.
-spec service_name_to_fqbin(_) -> no_return().
service_name_to_fqbin(X) -> error({gpb_error, {badservice, X}}).


%% Convert a a fully qualified (ie with package name) service name
%% and an rpc name, both as binaries to a service name and an rpc
%% name, as atoms.
-spec fqbins_to_service_and_rpc_name(_, _) -> no_return().
fqbins_to_service_and_rpc_name(S, R) -> error({gpb_error, {badservice_or_rpc, {S, R}}}).


%% Convert a service name and an rpc name, both as atoms,
%% to a fully qualified (ie with package name) service name and
%% an rpc name as binaries.
-spec service_and_rpc_name_to_fqbins(_, _) -> no_return().
service_and_rpc_name_to_fqbins(S, R) -> error({gpb_error, {badservice_or_rpc, {S, R}}}).


fqbin_to_msg_name(<<"push_token">>) -> pb_push_token;
fqbin_to_msg_name(<<"push_register">>) -> pb_push_register;
fqbin_to_msg_name(E) -> error({gpb_error, {badmsg, E}}).


msg_name_to_fqbin(pb_push_token) -> <<"push_token">>;
msg_name_to_fqbin(pb_push_register) -> <<"push_register">>;
msg_name_to_fqbin(E) -> error({gpb_error, {badmsg, E}}).


fqbin_to_enum_name(<<"push_token.Os">>) -> 'pb_push_token.Os';
fqbin_to_enum_name(E) -> error({gpb_error, {badenum, E}}).


enum_name_to_fqbin('pb_push_token.Os') -> <<"push_token.Os">>;
enum_name_to_fqbin(E) -> error({gpb_error, {badenum, E}}).


get_package_name() -> undefined.


%% Whether or not the message names
%% are prepended with package name or not.
uses_packages() -> false.


source_basename() -> "push.proto".


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned with extension,
%% see get_all_proto_names/0 for a version that returns
%% the basenames sans extension
get_all_source_basenames() -> ["push.proto"].


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned sans .proto extension,
%% to make it easier to use them with the various get_xyz_containment
%% functions.
get_all_proto_names() -> ["push"].


get_msg_containment("push") -> [pb_push_register, pb_push_token];
get_msg_containment(P) -> error({gpb_error, {badproto, P}}).


get_pkg_containment("push") -> undefined;
get_pkg_containment(P) -> error({gpb_error, {badproto, P}}).


get_service_containment("push") -> [];
get_service_containment(P) -> error({gpb_error, {badproto, P}}).


get_rpc_containment("push") -> [];
get_rpc_containment(P) -> error({gpb_error, {badproto, P}}).


get_enum_containment("push") -> ['pb_push_token.Os'];
get_enum_containment(P) -> error({gpb_error, {badproto, P}}).


get_proto_by_msg_name_as_fqbin(<<"push_register">>) -> "push";
get_proto_by_msg_name_as_fqbin(<<"push_token">>) -> "push";
get_proto_by_msg_name_as_fqbin(E) -> error({gpb_error, {badmsg, E}}).


-spec get_proto_by_service_name_as_fqbin(_) -> no_return().
get_proto_by_service_name_as_fqbin(E) -> error({gpb_error, {badservice, E}}).


get_proto_by_enum_name_as_fqbin(<<"push_token.Os">>) -> "push";
get_proto_by_enum_name_as_fqbin(E) -> error({gpb_error, {badenum, E}}).


-spec get_protos_by_pkg_name_as_fqbin(_) -> no_return().
get_protos_by_pkg_name_as_fqbin(E) -> error({gpb_error, {badpkg, E}}).



gpb_version_as_string() ->
    "4.13.0".

gpb_version_as_list() ->
    [4,13,0].
