%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.12.0

-ifndef(auth).
-define(auth, true).

-define(auth_gpb_version, "4.12.0").

-ifndef('PB_AUTH_PB_H').
-define('PB_AUTH_PB_H', true).
-record(pb_auth,
        {uid = 0                :: integer() | undefined, % = 1, 64 bits
         pwd = []               :: iodata() | undefined, % = 2
         cm = undefined         :: auth:pb_client_mode() | undefined, % = 3
         cv = undefined         :: auth:pb_client_version() | undefined, % = 4
         resource = android     :: android | ios | integer() | undefined % = 5, enum pb_auth.Resource
        }).
-endif.

-ifndef('PB_AUTH_RESULT_PB_H').
-define('PB_AUTH_RESULT_PB_H', true).
-record(pb_auth_result,
        {result = []            :: iodata() | undefined, % = 1
         reason = []            :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('PB_CLIENT_MODE_PB_H').
-define('PB_CLIENT_MODE_PB_H', true).
-record(pb_client_mode,
        {mode = active          :: active | passive | integer() | undefined % = 1, enum pb_client_mode.Mode
        }).
-endif.

-ifndef('PB_CLIENT_VERSION_PB_H').
-define('PB_CLIENT_VERSION_PB_H', true).
-record(pb_client_version,
        {version = []           :: iodata() | undefined, % = 1
         expires_in_seconds = 0 :: integer() | undefined % = 2, 64 bits
        }).
-endif.

-endif.
