%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.12.0

-ifndef(client_info).
-define(client_info, true).

-define(client_info_gpb_version, "4.12.0").

-ifndef('PB_CLIENT_MODE_PB_H').
-define('PB_CLIENT_MODE_PB_H', true).
-record(pb_client_mode,
        {mode = active          :: active | passive | integer() | undefined % = 1, enum pb_client_mode.Mode
        }).
-endif.

-ifndef('PB_CLIENT_VERSION_PB_H').
-define('PB_CLIENT_VERSION_PB_H', true).
-record(pb_client_version,
        {version = []           :: iodata() | undefined, % = 1
         expires_in_seconds = 0 :: integer() | undefined % = 2, 64 bits
        }).
-endif.

-endif.
