%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.12.0

-ifndef(push).
-define(push, true).

-define(push_gpb_version, "4.12.0").

-ifndef('PB_PUSH_TOKEN_PB_H').
-define('PB_PUSH_TOKEN_PB_H', true).
-record(pb_push_token,
        {os = android           :: android | ios | ios_dev | integer() | undefined, % = 1, enum pb_push_token.Os
         token = []             :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('PB_PUSH_REGISTER_PB_H').
-define('PB_PUSH_REGISTER_PB_H', true).
-record(pb_push_register,
        {push_token = undefined :: push:pb_push_token() | undefined % = 1
        }).
-endif.

-endif.
