%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.12.0

-ifndef(receipts).
-define(receipts, true).

-define(receipts_gpb_version, "4.12.0").

-ifndef('PB_SEEN_PB_H').
-define('PB_SEEN_PB_H', true).
-record(pb_seen,
        {id = []                :: iodata() | undefined, % = 1
         thread_id = []         :: iodata() | undefined, % = 2
         timestamp = 0          :: integer() | undefined % = 3, 64 bits
        }).
-endif.

-ifndef('PB_RECEIVED_PB_H').
-define('PB_RECEIVED_PB_H', true).
-record(pb_received,
        {id = []                :: iodata() | undefined, % = 1
         thread_id = []         :: iodata() | undefined, % = 2
         timestamp = 0          :: integer() | undefined % = 3, 64 bits
        }).
-endif.

-endif.
